### ISSUE TITLE
issue with ritual of the forest and terraforged world-gen

### ISSUE THREAD

**Issue by gerb82** [Ellpeck/NaturesAura#101]
So, i'm playing enigmatica 5, on a server that has terraforged world-gen enabled, and the ritual of the forest doesn't work (tried in multiple places to be sure)

So i did some digging, and here are my findings:
superflat - ritual works, even when i try to obstruct it with blocks (thought that might be the cause)
normal gen - same thing
terraforged gen - nothing, no matter how i mess with it

Tested recipes were ancient sapling, the aura gadget eye thing, and the nature's altar. I suspect the cause to be the fact that terraforged world-gen also makes trees grow in more unique shapes (the oaks usually have at least one log sticking out somewhere), and as a result, it breaks.
Or maybe it's something else, i'm not certain.

enigmatica 5 version used - 0.4.0
nature's aura version used - 23.3
terraforged version used - 1.15.2-0.0.10
forge version used - 31.1.30

**Comment by Ellpeck** [comment]
I assume this type of world has a custom dimension type associated with it. If that is the case, you have to add it to the Nature's Aura config of the server.

**Comment by gerb82** [comment]
How would i go about that? I'll try to test it and report back

**Comment by Ellpeck** [comment]
You can just go into the Nature's Aura config file and edit the `auraTypeOverrides` option according to its description

**Comment by gerb82** [comment]
round two of testing has produced some interesting results:

terraforged changes things IN the overworld, but it's still considered as the overworld
so the config did not work
however, the pack contains an ultra-amplified dimension thing, which is just an amplified world, that can be accessed even when terraforged is activated, and is not affected by it
as a result, the ritual could be performed in there, even with terraforged world-gen turned on, since the tree grew normally

sadly this portal appears to be creative-only, meaning that i still have no way to get through the mod in the pack as long as we have terraforged world-gen activated, leading me to ask for help here once more, now with the extra details

**Comment by Ellpeck** [comment]
O...kay? Well, you should report this issue to Terraforged then, since there's not really anything I can do on my end, I don't think.

**Comment by GryphonTheBard** [comment]
No clue if either of y'all care, but I brought this to the attention of the Terraforged dev (with the help of y'alls research) and we managed to get it fixed. The two mods should work together fine now. Thanks for the help!

**Comment by dags-** [comment]
It was just an event priority issue - I pushed my listener lower so that NA's runs first :]

**Comment by NillerMedDild** [comment]
This appears to be an issue again, have you altered your listener or something @dags-? :)
