### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by EnterFor** [Ellpeck/NaturesAura#102]
I don't know how it happens
[crash-2020-04-04_20.13.00-server.txt](https://github.com/Ellpeck/NaturesAura/files/4431303/crash-2020-04-04_20.13.00-server.txt)

**Comment by EnterFor** [comment]
One player said they destroyed a leaf whose name they couldn't remember

**Comment by Ellpeck** [comment]
Duplicate of #98
