### ISSUE TITLE
Delayed gameplay

### ISSUE THREAD

**Issue by crotin1111** [Ellpeck/NaturesAura#104]
So I have placed the wood made of golden. I have completed the 25 items step. But then the game starting running extremely slow with crazy delays. Running version 1.15.2
Mod version 23.5
Before that everything was fine. With 70+ mods. Issue started with the log placing guide

**Comment by Ellpeck** [comment]
Please install a mod like Lag Goggles to find the source of this lag, or alternatively, use the [built-in Minecraft profiler](https://mcforge.readthedocs.io/en/latest/gettingstarted/debugprofiler/) to find the source instead. If you don't understand the results of the profiler, you can post them here as well.
