### ISSUE TITLE
Curios Still Rendering When Set to False

### ISSUE THREAD

**Issue by TrueDakkon** [Ellpeck/NaturesAura#106]
So in my configs I have disabled Curios rendering, but for whatever reason they still render for your mod. Can you either fix this or create an option within your config to disable rendering? It would be nice as not everyone wants the rendering and some modpack devs don't use it due to inconsistencies with not all Curios items being rendered on the body.

**Comment by Ellpeck** [comment]
It's not rendering added by Curious, it's added by Nature's Aura. I can add a config option, though, yea.
