### ISSUE TITLE
Book of Natural Aura not progressing - 1.12.2

### ISSUE THREAD

**Issue by ProjectUmbra** [Ellpeck/NaturesAura#108]
When Natures Aura and Patchouli are installed alongside Reskillable, the Quests/Tasks in the mods guidebook don't progress despite the achievements unlocking correctly.

Forge 14.23.5.2838 (1.12.2)
Natures Aura 18.1
Reskillable 1.13.0
CompatSkills (Reskillable Addon) 1.17.0

Despite performing all the steps described in "Brilliant Trees" and obtaining the "Time = Brilliance" Advancement, the next task (presumably Ritual of the Forest) doesn't unlock in the book, and Brilliant Trees remains perpetually marked as a new quest/task.

Using /advancement grant @p from naturesaura:root unlocked all advancements, but didn't fix the book. There is nothing in the logs pertaining to the book, tasks or the mod in general when unlocking the advancements.

If this is an issue that's either too troublesome or impossible to fix, would it instead be possible to add a config option to Natures Aura that simply unlocks the whole book from the beginning, regardless of Advancement progression?

If any additional info is required, please do let me know. Thank you for looking into it!

**Comment by Ellpeck** [comment]
This is not an issue with Nature's Aura. Patchouli has the config option you're looking for.
