### ISSUE TITLE
crash on startup[1.15.2]

### ISSUE THREAD

**Issue by SDUBZ** [Ellpeck/NaturesAura#109]
Forge: 1.15.2-31.1.63
NA: NaturesAura-25.0

crash report:
[crash-2020-04-30_16.48.04-client.txt](https://github.com/Ellpeck/NaturesAura/files/4556581/crash-2020-04-30_16.48.04-client.txt)

logs:

[latest.log](https://github.com/Ellpeck/NaturesAura/files/4556582/latest.log)

**Comment by Ellpeck** [comment]
I assume this is an issue with Auraddons, since the latest version of Nature's Aura (sadly) had a breaking API change. Try removing Auraddons and see if the issue persists.

**Comment by SDUBZ** [comment]
okay i will try and thanks getting back to me i had a hunch it might be to do with the addon

**Comment by SDUBZ** [comment]
yes it was because the addon
