### ISSUE TITLE
Natures aura's fake player is not listed in FTB Utilities

### ISSUE THREAD

**Issue by mmis1000** [Ellpeck/NaturesAura#115]
It seems the FTB utility show the fake player by the fake player's profile.
The other mod ('like mekanism') do it this way.

https://github.com/mekanism/Mekanism/blob/3252d4a07ddd026c1275885dd4dd9e1ff588bf29/src/main/java/mekanism/common/Mekanism.java#L152
https://github.com/mekanism/Mekanism/blob/9a3fe1a5d78bb38fa963a3bcbc8d3846412315e4/src/main/java/mekanism/common/MekFakePlayer.java#L37

But this mod current spawn the fake player from factory directly without a name (the factory actully use a shared `[minecraft]` fake player).

https://github.com/Ellpeck/NaturesAura/blob/040f48b61295f29523dcd86e078764026f8c23b4/src/main/java/de/ellpeck/naturesaura/blocks/tiles/TileEntityPlacer.java#L110

Results in the fake player not listed in the ftb utilities.

**Comment by Ellpeck** [comment]
Nature's Aura uses Forge's built-in fake player.

**Comment by mmis1000** [comment]
That `is` forge's build-in fake player, there is also another method on the FakePlayerFactory that allow you to spawn a fake player with specific profile.

https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/common/util/FakePlayerFactory.java#L57

**Comment by Ellpeck** [comment]
I know there is. I don't want to spawn a fake player with a specific profile though. If every mod did that, you'd have to add hundreds of fake players to the blacklist of the protection mods you use.
