### ISSUE TITLE
[Suggestion] Add in your own Nature's Aura bottle instead of using Minecraft's

### ISSUE THREAD

**Issue by DWX12** [Ellpeck/NaturesAura#12]
While I'm a fan of using and integrating vanilla mechanics into a mod, too often do mods overlap with the same or similar mechanics, the bottle is one of those mechanics.

You might be familiar with Botania ender air and how to obtain it and how that has caused alot of frustration to players. If sneak right clicking in the end (was changed to that from earlier releases), a player obtains ender air; however, if a player is trying to gather dragon's breath, often times, they will also gather ender air, which results in clogging up their inventory.

So why not simply use sneak clicking to get aura? Again, it's the above scenario. There are other mods out there trying to do the same with bottles, which results in clogged inventories, wasted bottles, and frustrated players.

What I'm suggesting is to simply add in another bottle or item to capture aura, a tool that, when right clicked, will capture aura and fill any empty bottles in a player's inventory, or possibly some machine that can be filled with bottles and will produce aura filled bottles {although a solution, adds in just that much of an extra step of placing and breaking a machine when done).

I hope you'll consider this and implement something that will bypass this whole issue.

By the way, great start to the mod. Really reminds me of the very early days of Botania development.

Good job and thank you.

**Comment by superaxander** [comment]
Are you experiencing incompatibility with a specific mod?

**Comment by Ellpeck** [comment]
I wish players would for once actually test their complaints before reporting them.
There is no incompatibility with Ender Air, because it's specifically made so that right clicking on a block gets you Ender Air and right clicking on nothing gives you Bottled Darkness.

**Comment by superaxander** [comment]
Also I believe dragon's breath also requires someone to right click on a block, although I may have remembered that wrong.

**Comment by DWX12** [comment]
I was using Ender Air as an example and not as a compatibility issue. I was simply suggesting another method of getting bottled aura instead of right clicking with empty bottles to avoid any problems, issues, or annoyances with other mods using a similar mechanic.

But since you brought it up, with both NA and Botania installed and trying to get dragon's breath, how many bottles of non-dragon's breath are going to be acquired at the same time.

All I'm trying to say is this is an issue, albeit a very minor one, and an annoyance while trying to suggest an alternative method.

**Comment by PolarizedIons** [comment]
In case you missed it - it isn't an issue anymore ![https://i.imgur.com/l70upjE.png](https://i.imgur.com/l70upjE.png)

**Comment by Ellpeck** [comment]
(It never was an issue to begin with.)
