### ISSUE TITLE
Ancient wood [enhancement]

### ISSUE THREAD

**Issue by moulecake** [Ellpeck/NaturesAura#124]
Hi Ellpeck,

Your mod is really lovely, I did everything written on the book.

Now I am building a house with the ancient wood but there is no fence, no gate, no button, no trapdoor :'( 
Do you think you can add these stuff please ? :)

Bye
Moulecake

**Comment by Quarris** [comment]
To be fair at this point I wish there was a vanilla/forge feature to easily add these :P

**Comment by Ellpeck** [comment]
Added this to my trello todo list.
