### ISSUE TITLE
Undo of progress

### ISSUE THREAD

**Issue by TTRazzix** [Ellpeck/NaturesAura#125]
I've been loving the mod thus far. Only problem i've been getting however is that the mod is undoing my progress, locking up chapters of the book that i had previously unlocked and of i try and do the chapters again, nothing happens, meaning i can't progress further. 
As an example i have already made armor from ingots of the skies after i unlocked that chapter, but now i do not even have those chapters in the book anymore.

**Comment by Ellpeck** [comment]
Please report this to the Patchouli issue tracker.
