### ISSUE TITLE
Ritual of the forest not compatible with the Terraforged Oak saplings, likely others.

### ISSUE THREAD

**Issue by dudeloony** [Ellpeck/NaturesAura#139]
On Minecraft version 1.15.2 mod version 28.4
Pretty much what it says on the tin, every time I attempt the ritual of the forest with terraforged, it doesn't accept the ingredients. I tried it for both the token of joy and the token of fear. I believe it has something to do with the vanilla tree growing event being cancelled and replaced with the terraforged version.

**Comment by Ellpeck** [comment]
It needs to be the specific sapling mentioned in the recipe. Why does Terraforged have separate oak saplings to begin with?

**Comment by Ellpeck** [comment]
There's not really much I can do here. You can always use CraftTweaker's JSON Recipe editing system to change the Nature's Aura ritual of the forest recipes to use a different kind of sapling.

**Comment by NillerMedDild** [comment]
TerraForged does not have a seperate Oak Sapling, using a normal Minecraft Oak Sapling does not work.
OP suggested that the tree growing event has been altered
> I believe it has something to do with the vanilla tree growing event being cancelled and replaced with the terraforged version.

**Comment by Ellpeck** [comment]
Well, if the mod changes the event in a way that causes Nature's Aura's subscription to it not to be triggered, then there's nothing I can do on my end.

**Comment by NillerMedDild** [comment]
True, I should've searched the TF issue tracker before commenting here. 
They have previously fixed the incompatibility on their end, so I think they'll be willing to do so again.
