### ISSUE TITLE
Mod Interaction Issue - Astral Sorcery

### ISSUE THREAD

**Issue by ElahiKeru** [Ellpeck/NaturesAura#143]
Reference Issue Ticket Through Astral Sorcery: https://github.com/HellFirePvP/AstralSorcery/issues/1377

I noticed that through Astral Sorcery there's a telescope object which renders a night sky of stars for you to hunt down and define constellations, but recently i was unable to see anything rendering in the telescope gui, as referenced in the link above (including a screenshot of what it visually looks like). Once i took off the Aura Meter bauble and put it away in an inventory so that it didn't render the local aura in its meter, i was able to see stars again. I wanted to bring this up as a cross-mod issue to be looked into.

Thank you for your time!

**Comment by Ellpeck** [comment]
If you disable the `renderItemsOnPlayer` config, does this issue persist?

**Comment by ElahiKeru** [comment]
Sorry for the lag in response, Sadly I'm not the one directly in charge of the server in which I discovered the issue. I've reached out to the manager of it and will check in with them as soon as I can.

**Comment by ElahiKeru** [comment]
Sorry for the delay, I attempted what you suggested however it had no appreciable difference - i still could not see the stars in the telescope via Astral Sorcery. I would also like to point out that recently someone posted in the issue ticket I refer to in my original message and they have since started giving it more scrutiny on their end as well. Originally they had it tagged as "not their mod", and now they have removed said tag.

**Comment by Ellpeck** [comment]
Seems to be fixed on the other end. Closing for now.
