### ISSUE TITLE
net.minecraftforge.items.ItemStackHandler cannot be cast to de.ellpeck.naturesaura.api.aura.container.IAuraContainer

### ISSUE THREAD

**Issue by forebordingsky** [Ellpeck/NaturesAura#150]
Crashed when just walking around and now when it loads world it crashes again.

Crash-report: [crash-2020-10-20_21.00.27-client.txt](https://github.com/Ellpeck/NaturesAura/files/5410281/crash-2020-10-20_21.00.27-client.txt)

**Comment by Ellpeck** [comment]
What block were you looking at when this happened? It looks like a tile entity isn't handling capabilities correctly.

**Comment by forebordingsky** [comment]
I think it was Crate from DruidCraft mod

**Comment by Ellpeck** [comment]
This commit fixes the issue on their side, so I'm closing this issue. https://github.com/MysticMods/Druidcraft/commit/353287934663eb16b988352427e892bf9bc91cb3

**Comment by forebordingsky** [comment]
Ok, thanks. A problem was in old version of DruidCraft.
