### ISSUE TITLE
[1.15.2] Ritual Of The Forest Not Working (Sapling Refuses to Grow)

### ISSUE THREAD

**Issue by HockeyZman2000** [Ellpeck/NaturesAura#151]
(https://pastebin.pl/view/64f419c7)
(https://pastebin.pl/view/b07d3595)

I've previously gone through all of the past closed issues on GitHub to see if there was a solution to this specific issue before posting, but the only ones I've found that were similar was where the tree would grow but the ritual would not start with using TerraForged, which was fixed. I'm playing on a server with a custom modpack on the latest version of forge for 1.15.2. The problem I'm having specifically is that when placed in the middle of the ritual circle as outlined in the guide book and everywhere else, the sapling will NEVER grow. I've used over 5 stacks of bone meal in an attempt to grow it, I've waited for 3 in-game days for it to grow and nothing happens. If I place the sapling anywhere else, or if any part of the gold dust surrounding it is broken the sapling grows like normal. Sometimes however I will get the crash pasted above, which I'm assuming is what happens when the tree tries to grow. If someone could point me in the right direction to solve this or give any help I would greatly appreciate it! I've also included the latest log from the server if it is useful.

**Comment by Ellpeck** [comment]
Please try to reproduce this issue with just Nature's Aura installed. If it doesn't occur, try finding out which mod in your pack causes it.

**Comment by HockeyZman2000** [comment]
It appears that Performant just simply has a lot of incompatibility issues with many other mods. First mod I tested it with too. Thanks.
