### ISSUE TITLE
no fake player ? ftb claim blocks planting 

### ISSUE THREAD

**Issue by Gayanfalor** [Ellpeck/NaturesAura#152]
Hello, i just spotted that the imperceptible builder cant plant saplings while its in ftb utils claim zone.

I had a question too with the canopy diminisher, is the sapling need to be included in the zone ? because i have put the canopy 10 block over where the trees are, normally its in the zone with the magnifier but a big tree has spawned and it was in the zone. Maybe the claim zone too.

thanks

i play on tnp limitless 3 nature's aura ver 31.0
mc 1.16.3

**Comment by Ellpeck** [comment]
The sapling needs to be in the zone of the block, because that's the only thing that it checks for.
Also, the imperceptible builder uses the default Forge fake player, whose name is `[Minecraft]` and whose UUID is `41C82C87-7AfB-4024-BA57-13D2C99CAE77`.

**Comment by Gayanfalor** [comment]
it is in the zone, i'll try to add minecraft as ally.

Btw is is normal that the canopy sometimes doenst works ? i got a big tree in the zone of the canopy

**Comment by Ellpeck** [comment]
I can't reproduce that issue in 1.16.3. It might be interaction with another mod that messes it up.

**Comment by Gayanfalor** [comment]
i tried adding the fake players but its still making the noise as if its planting sapling but does nothing. Btw unclaiming the chunk is working and planting works dunno whats doing that

**Comment by Ellpeck** [comment]
Are you sure you have fake players allowed in your claim settings in general? With FTB chunks, there's a separate "Allow fake players" option.

**Comment by Gayanfalor** [comment]
i'll check
