### ISSUE TITLE
Crashing when i try to grow the sappling for the ritual of the forest

### ISSUE THREAD

**Issue by PixelatedChaoz** [Ellpeck/NaturesAura#154]
I've been trying to get into nature's aura on the mod pack HR: New Beginnings but when I try to grow the sappling by waiting it crashes, also I've tried lots and lots of bonemeal around 2 stacks but that didn't work either, when I set the gamerule randomTickSpeed to 2000 it just crashes and when I load back in the sappling didn't grow

attached below is the crash log

[crash-2020-11-05_16.43.03-server.txt](https://github.com/Ellpeck/NaturesAura/files/5499814/crash-2020-11-05_16.43.03-server.txt)

**Comment by lucas41205** [comment]
I had the exact same issue on a HR: New Beginnings server I was hosting. Were you able to fix the issue?

**Comment by mmb88** [comment]
As mentioned in #151 is the performant mod a problem.
I have deleted this mod an now it works fine :)
