### ISSUE TITLE
Debug log found some errors 

### ISSUE THREAD

**Issue by BedrockLegends** [Ellpeck/NaturesAura#155]
****************** Blame Report 1.16.3-1.4.7 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:warped_aura_mushroom"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [byg:sythian_torrids, byg:embur_bog, byg:magma_wastes, byg:withering_woods, byg:wailing_garth, byg:glowstone_gardens, minecraft:nether_wastes, minecraft:warped_forest, minecraft:soul_sand_valley,
                   minecraft:basalt_deltas, byg:warped_desert, byg:quartz_desert, byg:weeping_mire, minecraft:crimson_forest, byg:subzero_hypogeal, byg:crimson_gardens, byg:brimstone_caverns]

**Comment by BedrockLegends** [comment]
[08Nov2020 16:31:19.212] [main/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.16.3-1.4.7 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:crimson_aura_mushroom"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [byg:sythian_torrids, byg:embur_bog, byg:magma_wastes, byg:withering_woods, byg:wailing_garth, byg:glowstone_gardens, minecraft:nether_wastes, minecraft:warped_forest, minecraft:soul_sand_valley,
                   minecraft:basalt_deltas, byg:warped_desert, byg:quartz_desert, byg:weeping_mire, minecraft:crimson_forest, byg:subzero_hypogeal, byg:crimson_gardens, byg:brimstone_caverns]

**Comment by BedrockLegends** [comment]
[08Nov2020 16:31:19.213] [main/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.16.3-1.4.7 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:aura_cactus"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [byg:lush_red_desert, minecraft:desert, byg:red_desert, byg:oasis, minecraft:desert_hills, byg:canyon_edge, byg:shrublands, byg:mojave_desert, byg:dunes,
                   byg:red_desert_dunes, byg:canyons, minecraft:desert_lakes]

**Comment by BedrockLegends** [comment]
[08Nov2020 16:31:19.214] [main/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.16.3-1.4.7 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:aura_bloom"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [minecraft:frozen_ocean, byg:evergreen_hills, byg:great_lake_isles, byg:marshlands, minecraft:swamp, minecraft:basalt_deltas, good_nights_sleep:lollipop_lands, minecraft:snowy_taiga_hills, minecraft:dark_forest,
                   byg:meadow, byg:seasonal_forest, appliedenergistics2:spatial_storage, minecraft:giant_spruce_taiga, byg:alps, byg:bulbis_gardens, byg:tropical_fungal_forest, byg:tropical_islands, byg:aspen_forest,
                   byg:enchanted_forest_hills, byg:zelkova_forest_hills, byg:frozen_lake, minecraft:nether_wastes, byg:white_beach, minecraft:deep_lukewarm_ocean, byg:seasonal_birch_forest, byg:guiana_clearing, minecraft:snowy_taiga,
                   byg:brimstone_caverns, minecraft:stone_shore, good_nights_sleep:dreamy_forest, byg:boreal_forest_hills, minecraft:bamboo_jungle_hills, byg:amaranth_fields, byg:the_black_forest, byg:blue_giant_taiga, minecraft:tall_birch_forest,
                   minecraft:modified_wooded_badlands_plateau, byg:magma_wastes, good_nights_sleep:wasted_forest, byg:maple_taiga, minecraft:plains, minecraft:modified_badlands_plateau, byg:canyon_edge, byg:shulkren_forest, byg:red_oak_forest,
                   byg:dummy, byg:seasonal_giant_taiga, good_nights_sleep:shameful_plains, minecraft:ocean, byg:wooded_grassland_plateau, minecraft:warped_forest, minecraft:cold_ocean, byg:ivis_fields, minecraft:badlands,
                   byg:seasonal_birch_forest_hills, minecraft:wooded_badlands_plateau, byg:snowy_evergreen_clearing, byg:jacaranda_clearing, byg:snowy_black_beach, byg:snowy_blue_giant_taiga, minecraft:deep_warm_ocean, byg:black_forest_clearing, minecraft:giant_tree_taiga_hills,
                   byg:zelkova_forest, minecraft:taiga_hills, byg:deciduous_clearing, byg:redwood_mountains, minecraft:giant_tree_taiga, byg:sierra_range, byg:weeping_witch_clearing, minecraft:crimson_forest, byg:bamboo_forest,
                   byg:prairie_clearing, byg:wooded_meadow, minecraft:forest, minecraft:end_midlands, byg:oasis, byg:coral_mangroves, byg:forest_fault, minecraft:sunflower_plains, minecraft:gravelly_mountains,
                   byg:withering_woods, byg:dover_mountains, byg:sierra_valley, byg:snowy_deciduous_forest_hills, byg:ebony_hills, minecraft:desert, minecraft:beach, byg:seasonal_forest_hills, byg:guiana_shield,
                   byg:pointed_stone_forest, byg:red_rock_highlands, byg:red_desert_dunes, byg:glowshroom_bayou, byg:seasonal_deciduous_forest, byg:snowy_deciduous_forest, byg:crag_gardens, byg:prairie, byg:snowy_deciduous_clearing,
                   minecraft:desert_lakes, minecraft:dark_forest_hills, byg:polluted_lake, byg:red_spruce_taiga, byg:ebony_woods, byg:crimson_gardens, minecraft:modified_jungle_edge, byg:shattered_glacier, byg:red_rock_lowlands,
                   minecraft:giant_spruce_taiga_hills, byg:bog, minecraft:swamp_hills, byg:zelkova_clearing, byg:tropical_rainforest, minecraft:birch_forest, minecraft:mountains, minecraft:soul_sand_valley, byg:orchard,
                   byg:quartz_desert, good_nights_sleep:sleepy_hills, byg:blue_taiga, byg:basalt_barrera, byg:flowering_grove, byg:pumpkin_forest, minecraft:modified_jungle, byg:seasonal_deciduous_clearing, byg:shrublands,
                   byg:coniferous_forest, byg:blue_taiga_hills, byg:snowy_coniferous_clearing, byg:aspen_clearing, byg:twilight_valley_hills, byg:coniferous_forest_hills, minecraft:modified_gravelly_mountains, byg:cryptic_wastes, byg:red_oak_forest_hills,
                   byg:ethereal_islands, good_nights_sleep:hopeful_fields, byg:warped_desert, good_nights_sleep:good_dream_plains, byg:jacaranda_forest, byg:rainbow_beach, minecraft:desert_hills, byg:twilight_valley, minecraft:jungle_hills,
                   minecraft:mushroom_field_shore, minecraft:snowy_tundra, byg:grassland_plateau, minecraft:frozen_river, byg:wooded_red_rock_mountains, byg:flowering_enchanted_grove, byg:red_desert, byg:deciduous_forest_hills, minecraft:deep_ocean,
                   byg:cherry_blossom_clearing, byg:embur_bog, byg:dead_sea, byg:glowstone_gardens, byg:viscal_isles, byg:boreal_clearing, minecraft:mountain_edge, byg:fresh_water_lake, minecraft:river,
                   byg:enchanted_forest, byg:coniferous_clearing, minecraft:the_void, byg:weeping_witch_forest, byg:nightshade_forest, byg:glowing_ancient_forest, minecraft:wooded_hills, byg:seasonal_taiga_hills, minecraft:deep_cold_ocean,
                   byg:canyons, byg:mangrove_marshes, minecraft:end_highlands, byg:black_forest_hills, minecraft:eroded_badlands, byg:cika_mountains, byg:tropical_fungal_rainforest_hills, byg:snowy_coniferous_forest, byg:araucaria_savanna,
                   byg:lush_tundra, byg:lush_red_desert, byg:rose_fields, byg:bayou, byg:woodlands, byg:snowy_coniferous_forest_hills, byg:maple_hills, minecraft:birch_forest_hills, byg:bluff_peaks,
                   byg:red_rock_mountains, minecraft:snowy_beach, byg:aspen_forest_hills, byg:skyris_highlands, byg:great_lakes, minecraft:jungle, byg:boreal_forest, byg:wailing_garth, byg:cika_woods,
                   byg:shattered_desert, byg:cold_swamplands, byg:weeping_mire, byg:fungal_patch, byg:redwood_tropics, byg:seasonal_deciduous_forest_hills, byg:redwood_clearing, minecraft:tall_birch_hills, minecraft:snowy_taiga_mountains,
                   byg:enchanted_grove, byg:sythian_torrids, minecraft:savanna_plateau, minecraft:taiga, minecraft:wooded_mountains, minecraft:savanna, minecraft:jungle_edge, byg:purpur_peaks, minecraft:ice_spikes,
                   byg:allium_fields, byg:snowy_rocky_black_beach, byg:evergreen_taiga, byg:dunes, minecraft:lukewarm_ocean, byg:bluff_steeps, byg:flowering_meadow, minecraft:mushroom_fields, byg:snowy_blue_taiga_hills,
                   minecraft:warm_ocean, byg:alpine_foothills, byg:flowering_ancient_forest, byg:snowy_blue_taiga, byg:ancient_forest, byg:grove, minecraft:flower_forest, byg:tropical_rainforest_hills, minecraft:shattered_savanna_plateau,
                   minecraft:deep_frozen_ocean, byg:seasonal_taiga, byg:mojave_desert, byg:cherry_blossom_forest, minecraft:shattered_savanna, byg:autumnal_valley, byg:stone_forest, byg:vibrant_swamplands, byg:snowy_evergreen_taiga,
                   byg:baobab_savanna, minecraft:bamboo_jungle, byg:araucaria_forest, minecraft:end_barrens, byg:subzero_hypogeal, minecraft:small_end_islands, minecraft:badlands_plateau, minecraft:the_end, minecraft:taiga_mountains,
                   byg:cypress_swamplands, byg:rocky_beach, byg:evergreen_clearing, byg:deciduous_forest, good_nights_sleep:nightmare_hills, byg:northern_forest, byg:jacaranda_forest_hills, byg:snowy_evergreen_hills, minecraft:snowy_mountains]

**Comment by Ellpeck** [comment]
I register my features the exact same way as some other mods I looked at, so I'm not really sure what this is about. If this starts actually causing any issues, please reopen the issue.
