### ISSUE TITLE
Custom Animal_Spawner recipes don't appear on Altar of Birthing 'uses' in JEI.

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/NaturesAura#156]
Version: NaturesAura-32.0

I've added some custom spawning recipes via KubeJS, and noticed that the altar of Birthing doesn't update properly in JEI.

If I look at the uses for the Altar, it only shows the default summons. If, however, I look at the uses on the reagents themselves (spirit of birthing, for instance) it shows the new spawns correctly.

**Comment by Ellpeck** [comment]
I.. am honestly not sure what I could do about this, since I just register the recipe category in JEI like normal and use the vanilla recipe system. Does this happen with any other recipe types in the mod?

**Comment by MuteTiefling** [comment]
I haven't noticed, but I also haven't made any other custom recipes yet.

I'll do some more testing tonight to see if it's something else being goofy.

**Comment by MuteTiefling** [comment]
Well, scratch the whole thing. I'm not sure when or how it started working, but it is working now. All of the custom recipes are showing up in JEI when checking the uses of either the Altar of Birthing or the Spirits of Birthing. Sorry for the trouble!
