### ISSUE TITLE
[Enhancement] Add particles when the player forgets to add the gold powder to the Ritual of the Forest

### ISSUE THREAD

**Issue by gamma-delta** [Ellpeck/NaturesAura#160]
Re: Dire's video today, if tons of people forget to put the gold powder, maybe the mod should help them along.

I would propose a bunch of particles (smoke maybe?) hissing out of the ground where the powder is supposed to go if a sapling grows without any powder.

Perhaps you can also prevent the sapling from growing by cancelling the event maybe, I don't know, I'm not that skilled of a modder. (Otherwise I would open a PR.) (I might still try and open a PR.)

**Comment by Ellpeck** [comment]
I haven't seen any videos of people forgetting the gold powder, and then *not realizing that they forgot it*. They always just say "oh, I forgot the gold powder" after a few seconds and then tend not to forget it again. For that reason, I don't think there's any change in the way the ritual of the forest works necessary.
