### ISSUE TITLE
Disentangler of Mortals does not function

### ISSUE THREAD

**Issue by Allyraya** [Ellpeck/NaturesAura#162]
I made the Disentangler of Mortals.

I placed it near a world-generated sheep.

I expected the sheep to die, as a test of the range of the DoM.

The sheep did not die.
![2020-11-29_19 53 31](https://user-images.githubusercontent.com/39148273/100558610-19cb8080-327d-11eb-98f4-e55bf27fe2cf.png)

![2020-11-29_19 58 29](https://user-images.githubusercontent.com/39148273/100558657-4bdce280-327d-11eb-97b6-4bb4e407f8b1.png)

**Comment by Ellpeck** [comment]
I probably should've known this since I made the mod, but I also forgot, so here you go:
![image](https://user-images.githubusercontent.com/5741138/100562961-78185380-32bd-11eb-8835-365d98912d7e.png)
