### ISSUE TITLE
[1.15.2] Particle rendering breaks on contact with Astral Sorcery

### ISSUE THREAD

**Issue by incomingnerd** [Ellpeck/NaturesAura#164]
*Problem*
Astral Sorcery triggers a rendering bug with Nature's Aura particles, resulting in them appearing as untextured quads.

*To reproduce*
1. Create an MC 1.15 instance with both Astral Sorcery and Nature's Aura.
2. Start a new Creative world.
3. Grow an ancient sapling and place an Astral Collector Crystal next to it.
4. Observe the broken square particles.

*Versions*
MC 1.15.2
Forge 31.2.47
Astral Sorcery 1.12.13
Nature's Aura 28.5

**Comment by Ellpeck** [comment]
The 1.15 version of Nature's Aura is not supported anymore. If this issue still occurs in the 1.16 version, please re-open this issue.

**Comment by incomingnerd** [comment]
Just tested. Still very much broken.

*Versions*
MC 1.16.4
AS 1.13.1
NA 33.1
