### ISSUE TITLE
[1.16.4] Particle rendering breaks on contact with Astral Sorcery

### ISSUE THREAD

**Issue by incomingnerd** [Ellpeck/NaturesAura#165]
**Problem**
Astral Sorcery triggers a rendering bug with Nature's Aura particles, resulting in them appearing as untextured quads.

**To reproduce**
1. Create an MC 1.15 or 1.16 instance with both Astral Sorcery and Nature's Aura.
2. Start a new Creative world.
3. Grow an ancient sapling and place an Astral Collector Crystal next to it.
4. Observe the broken square particles.

**Versions**
MC 1.16.4
Forge 35.1.7
Astral Sorcery 1.13.1
Nature's Aura 33.1

**Comment by incomingnerd** [comment]
Same bug as present in 1.15 #164

**Comment by incomingnerd** [comment]
![2020-12-03_21 17 13](https://user-images.githubusercontent.com/43726486/101089347-f4a47e00-35ac-11eb-8069-ca7e99cad5b4.png)

**Comment by Ellpeck** [comment]
Does this issue occur with any other mod with custom rendering? 
Also, does the Astral rendering cause any other mod's particles to break?

**Comment by incomingnerd** [comment]
I've not had a chance to do any extensive testing, but Botania (which is pretty particle heavy) seemed unaffected. If you can think of any 1.15/1.16 mods that might provoke it I'd be happy to install them and give it a test

**Comment by incomingnerd** [comment]
I don't know if this helps, but the AS collector crystal particles are one of the few particle systems I've seen which fade out at the single-player pause menu. On disappearing the NA particles return to normal and will break again as soon as the menu is closed.

**Comment by Ellpeck** [comment]
Can you also report this to Astral Sorcery, please? It might be Nature's Aura's issue, but it might also be AS's. That way, we can both do testing :)

**Comment by Ellpeck** [comment]
Please try with [this build](https://ci.ellpeck.de/job/NaturesAura/job/main/18/artifact/build/libs/NaturesAura-33.1.18.jar) to confirm that this issue is fixed.

**Comment by incomingnerd** [comment]
Yes, this does fix the issue for 1.16.4. Sadly I am stuck on 1.15 for now, as my pack relies on Create and the 0.3 release of that mod is still in closed testing and development (with no announced release date). Thanks anyway.
