### ISSUE TITLE
Ritual of the Forest doesn't work with Dynamic Trees

### ISSUE THREAD

**Issue by DarkWolfe5** [Ellpeck/NaturesAura#167]
I've tried various ways to get Dynamic Trees to work with the Ritual of the forest with little success.
There's a setting in CT I can turn off and it'll work, but that defeats the purpose of having Dynamic Trees!
(replaceVanillaSapling  which replaces vanilla saplings with DT saplings when planted, so whatever you plant, you get a dynamic tree)

From what I can see in the code of both mods, DT trees are registered as just blocks, but NA is looking fort BlockSapling || BlockLog.

Is there any way to add compatibility for rituals, etc with dynamic trees?

P.S. Dynamic Trees - Nature's Aura (by HarleyOConnor) only adds dynamic trees for the species added in NA. It does NOT seem to fix the Ritual incompatibility. :-(

**Comment by Harleyoc1** [comment]
I haven’t gotten around to implementing the Ritual yet, and as I replied just now on the dynamic trees extra combat GitHub, I will release a patch as soon as possible to remove `replaceVanillaSapling` support for the time being. Please open any issues with Dynamic Trees compatibility in [my repository](https://github.com/Harleyoc1/DynamicTreesNaturesAura) for DT compat.

**Comment by Ellpeck** [comment]
I don't think this is a Nature's Aura issue, since it just expects vanilla trees to exist, which is a pretty reasonable expectation.

It looks like @Harleyoc1 is planning on adding this compatibility anyway.

**Comment by DarkWolfe5** [comment]
Wow, I wasn't expecting such quick responses! Thank you both!!
