### ISSUE TITLE
Missing register

### ISSUE THREAD

**Issue by smallerYeet** [Ellpeck/NaturesAura#169]
There are missing registers in my log that Blame found, please fix them!
I use the latest version of this mod with the latest Forge and Minecraft 1.16.4

****************** Blame Report 1.7.4 ******************

 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "naturesaura:warped_aura_mushroom"
    },
    "decorator": {
      "config": {},
      "type": "minecraft:nope"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [biomesoplenty:visceral_heap, biomesoplenty:undergrowth, biomesoplenty:withered_abyss, biomesoplenty:crystalline_chasm, minecraft:crimson_forest, minecraft:nether_wastes, minecraft:soul_sand_valley,
                   minecraft:basalt_deltas, minecraft:warped_forest]
[latest.log](https://github.com/Ellpeck/NaturesAura/files/5703424/latest.log)

**Comment by Ellpeck** [comment]
already fixed in dev
