### ISSUE TITLE
Natural altar does not work in a void dimension.

### ISSUE THREAD

**Issue by levicc00123** [Ellpeck/NaturesAura#171]
![2020-12-22_00 52 46](https://user-images.githubusercontent.com/4361838/102864501-75f37180-43f1-11eb-924f-c60d2ba87ddd.png)

In my case, I'm living in the void dimension from Just Another Void Dimension 2.5.24. I've checked that the area I've built in has enough aura, and triple checked that I've built it correctly, but it's still not drawing in aura. Am I being an idiot?

Minecraft 1.16.4
Forge 31.1.13
MCP 20201102.104115
Nature's Aura 33.2
Patchouli 48

Thank you for your consideration.

**Comment by Ellpeck** [comment]
Add the dimension type to the "aura type overrides" config.
