### ISSUE TITLE
[1.16.4] Hopper Enhancement not working on Adept Hoppers

### ISSUE THREAD

**Issue by anabsolutesloth** [Ellpeck/NaturesAura#173]
Mod Version(s): NaturesAura-33.2, Patchouli-1.16.4-48.jar
Modlist is that of Direwolf20 1.16: https://www.feed-the-beast.com/modpack/ftb_presents_direwolf20_1_16
![2020-12-29_20 14 22](https://user-images.githubusercontent.com/63694982/103329862-9f288900-4a13-11eb-821a-c28cf9279a9c.png)
![2020-12-29_20 14 33](https://user-images.githubusercontent.com/63694982/103329863-a059b600-4a13-11eb-9948-6ba6bc650422.png)
The device was given time to act, and it does infact work on standard Hoppers, the Aura where a standard Hopper was tested was significantly lower than the area where the Adept Hopper is.

**Comment by anabsolutesloth** [comment]
Hmm, a little later after a Nether visit, it started working, i have no clue, probably still something to investigate.

**Comment by Ellpeck** [comment]
I can't reproduce this issue. Please try with just Nature's Aura installed.

**Comment by anabsolutesloth** [comment]
Cloned the World into a separate instance with only Patchouli and Nature's Aura installed to no avail.
![2020-12-30_14 47 48](https://user-images.githubusercontent.com/63694982/103385240-6d183500-4aae-11eb-98f9-9f4c923430b0.png)
However, locations near spawn on new worlds on both the new instance and primary instance worked.
I should also note that it has stopped working on the main world.

And here is the Aura level on the main world.
![image](https://user-images.githubusercontent.com/63694982/103385334-cc764500-4aae-11eb-8638-62cdfa6738a8.png)
The new worlds had about half full Aura.

And lastly, it should be noted that there are two sets of Aura Field Creators shearing Vines up above.
![2020-12-29_23 43 23](https://user-images.githubusercontent.com/63694982/103385993-9e463480-4ab1-11eb-91d5-a766fe630efa.png)

**Comment by anabsolutesloth** [comment]
A bit more testing shows that it does not work in the area where the Ancient Tree was grown prior, it is not an issue with the chunk.

**Comment by Ellpeck** [comment]
Cannot reproduce this issue, even with vines and ancient trees around.

Are you sure that you didn't just accidentally set the adept hopper to blacklist mode (by right-clicking it)? You should be able to see the current mode using the Environmental Eye.
