### ISSUE TITLE
Ancient trees are not working in nether

### ISSUE THREAD

**Issue by Ritzumi** [Ellpeck/NaturesAura#178]
### Version 
Forge: 35.1.36
Nature aura: 33.3

### Description
The ancient tree leaves won't get drained in nether and the aura around won't get stabilize.

### Step to reproduce
1. Create a world
2. Enter nether dimension
3. Drain aura dry
4. Plant an ancient tree and observe its leaves
5. Behold~

### Attachment
Picture: https://imgur.com/a/vlokiF7

**Comment by Ellpeck** [comment]
This is intended behavior. If you read the section that explains the basics of aura, it explains that certain aura mechanics don't work in certain dimensions, and since overworld plants don't really grow in the nether, they also don't have an effect on the ghostly aura there.
