### ISSUE TITLE
[Feature Request] Non-Overworld Dimensions

### ISSUE THREAD

**Issue by Yashimata** [Ellpeck/NaturesAura#18]
It doesn't seem like the mod does much in the non-overworld dimensions. There's aura, and it can be drained or bottled, but it doesn't seem like it can be replenished. Ancient Trees can be grown and the absorber will eat flowers, but neither will replenish the aura at all. 

So, would it be possible to let many of the mod's features work in other dimensions? Or, if it's not intended to work in non-overworld dimensions, would it be possible to add a config to 'allow' modded dimensions to be treated as an overworld?

**Comment by Ellpeck** [comment]
No, I'm sorry. The Potion generator works in all dimensions and obviously there are more features to come, but I very much enjoy that the mod is dimension-bound.

**Comment by Ellpeck** [comment]
That's true. I didn't really think about modded dimensions in connection to NA yet, and I think for the Nether and the End, it's pretty obvious that neither a tree- nor a flower-based generator works there.
I'll add a config option that allows you to override the aura types of any dimensions that don't have a set type.
