### ISSUE TITLE
[Help Wanted] Aura Trove and Cache items do not show on player in enigmatica6

### ISSUE THREAD

**Issue by theboo** [Ellpeck/NaturesAura#181]
I have tested with every mod that has been added to e6 after nature's aura was added and they do show on the character, but with the whole pack they do not. Issue exists on single player and servers in  enigmatica 6 v0.3.5

**Comment by Ellpeck** [comment]
Not sure what to do about this without knowing what combination of mods causes this issue, to be honest :(

**Comment by theboo** [comment]
You know you want to dedicate an entire day to binary testing!

**Comment by Ellpeck** [comment]
Closing this for now, as it's not reproduceable outside of this modpack.
