### ISSUE TITLE
[1.16.4] Lag when there are a lots of auras in a big area

### ISSUE THREAD

**Issue by mmis1000** [Ellpeck/NaturesAura#189]
### Mod Version
1.16.4-1.8.6 (in Direwolf 20 1.16.4 - 1.5.1)

### What happened
we spawn a lots of auras in the server with setup like this (use the mekanism to generate mossy cobblestone infinitely)
![圖片](https://user-images.githubusercontent.com/2993977/106295011-deecc580-628a-11eb-8681-3e2f9595b009.png)
And the server lags very seriously for some reason even we already literally remove every block in the loaded chunks.
![圖片](https://user-images.githubusercontent.com/2993977/106295469-73572800-628b-11eb-9851-b8fb36195837.png)

### The problem
We profiled the server with the `spark` profiler.
And it turns out.
The natures aura cause big lag when there are a lots of aura in the near by area.
It use 20s in 60s on Ryzen 3900x. 
It is giant amounts of cpu power as regards 3900 is a high frequency x86 cpu.
It may be even worse in most of setups (vgpu of vps, core i5, whatever).

https://spark.lucko.me/#5zG1urtoxG
![圖片](https://user-images.githubusercontent.com/2993977/106293749-515ca600-6289-11eb-8023-5f7ea508f338.png)

The performance profile suggests a lot of time used in `de.ellpeck.naturesaura.api.aura.chunk.IAuraChunk.getLowestSpot()`, `de.ellpeck.naturesaura.api.aura.chunk.IAuraChunk.getSpotAmountInArea()` and so on.

Probably loops across all aura chunk in the server is not a good idea when there are a lots of them.

**Comment by Ellpeck** [comment]
It would be great if you could test this exact setup using [this version](https://ci.ellpeck.de/job/NaturesAura/job/main/45/artifact/build/libs/NaturesAura-33.4.45.jar) and let me know two things:
- Does everything actually still work as intended? (ie did any gameplay change)
- Is the performance improved? (you can just attach another profile for this)
If everything still works and the performance did in fact improve, then I will publish an update shortly.

**Comment by mmis1000** [comment]
![圖片](https://user-images.githubusercontent.com/2993977/106358044-baedba80-6344-11eb-95b7-0d833881e0f5.png)
https://spark.lucko.me/#yRCgd8Qxbk

Didn't seems to do anything.
Still lag.

**Comment by mmis1000** [comment]
The world we encountered this problem (Direwolf 1.16.4 - 1.5.1)
https://drive.google.com/file/d/1ke_k9SaMmoxgIEoARuUFRNyI6rmQFpmn/view?usp=sharing

**Comment by Ellpeck** [comment]
I checked out your save. For the amount of aura you added to this area (it was probably chunkloaded for a very long time?), the lag is.. very minor. When doing my own profiling tests, the amount of lag caused by the aura in the area is an amount that is definitely to be expected.

You should probably check out the Aura Detector, which is a device that you're supposed to use to disable aura generation after a certain threshold is reached.

**Comment by mmis1000** [comment]
Then... Is there a way to reset aura of a big area?
I saw that command used to have a range parameter from another issue.
But it seems it is no longer there.
The 35 block range is way too short given the server defaults to chunk load 10 * 10 chunks.

**Comment by Ellpeck** [comment]
Just fly around and use it multiple times.
