### ISSUE TITLE
Ritual of Forest with Bewitchment saplings

### ISSUE THREAD

**Issue by DarkWolfe5** [Ellpeck/NaturesAura#193]
### Expected Behavior
When a Cypress, Elder, or Juniper sapling is placed in the middle of a Nature Aura's Tree Ritual multi-block
When the sapling grows into a full-size tree, the ritual SHOULD be kicked off and you'd see gold particles floating towards the tree, before it disappears, dropping the crafted item.

### Actual Behavior
When Cypress, Elder, or Juniper sapling grows to a full tree, NOTHING happens. No ritual completion, just a big tree in the center.
For whatever reason, the Dragon's Blood sapling DOES work.

### Steps to Reproduce
Add script adding simple recipe to /scripts folder (Example below)
Build Nature Aura's Tree Ritual multiblock. 
Add ingredients for any recipe onto the wood stands.
Plant Cypress, Elder, or Juniper sapling in center of multi-block.
Either bone meal the sapling until it grows, wait for it naturally, or kick up the RandomTickRate and wait less.

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Minecraft: 1.12.2
Forge: 1.12.2-forge-14.23.5.2854
Bewitchment: 1.12.2-0.0.22.55
Patchouli: 1.0-23.6
Baubles: 1.12-1.5.2
Nature's Aura: 18.1
MTLib: 3.0.6
JEI: 1.12.2-4.15.0.291
InventoryTweaks: 1.64+dev.151
CraftTweaker2: 1.12.2-4.1.20.609
Base: 1.12.2-3.13.0
ContentTweaker: 1.12.2-4.9.1

### Example recipe script: 
MC_instance/scripts/basic.zs
```
mods.naturesaura.TreeRitual.addRecipe("test0",              <ore:treeSapling>,                     <minecraft:egg>, 50, [<minecraft:gravel>]);
mods.naturesaura.TreeRitual.addRecipe("test1",              <bewitchment:dragons_blood_sapling>,   <minecraft:egg>, 50, [<minecraft:gravel>]);
mods.naturesaura.TreeRitual.addRecipe("test2",              <bewitchment:cypress_sapling>,         <minecraft:egg>, 50, [<minecraft:gravel>]);
mods.naturesaura.TreeRitual.addRecipe("test3",              <bewitchment:elder_sapling>,           <minecraft:egg>, 50, [<minecraft:gravel>]);
mods.naturesaura.TreeRitual.addRecipe("test4",              <bewitchment:juniper_sapling>,         <minecraft:egg>, 50, [<minecraft:gravel>]);
```

**Comment by Ellpeck** [comment]
Sorry, support for 1.12 has been dropped. Please try to reproduce this issue in 1.16.x.
