### ISSUE TITLE
Guidebook breaks when recipes are changed via KubeJS

### ISSUE THREAD

**Issue by truenachtara** [Ellpeck/NaturesAura#194]
In my scripts folder I have these: 
```javascript
event.remove({id: 'naturesaura:altar/infused_stone'})

event.custom({
    "type": "naturesaura:altar",
    "input": {
        "item": "elementalcraft:whiterock"
    },
    "output": {
        "item": "naturesaura:infused_stone"
    },
    "aura_type": "naturesaura:overworld",
    "aura": 7500,
    "time": 40
})
```

However, doing this causes the guidebook to break.
![image](https://user-images.githubusercontent.com/16340367/107895012-52cbd680-6ef7-11eb-9d2b-d31cef2cd6e5.png)

Logs: https://pastebin.com/ELiu2VBR

**Comment by Ellpeck** [comment]
It doesn't look like you gave the new recipe the same name that the old recipe had. If you don't want to do that, you have to remove the page in the book using a patchouli override book json.
