### ISSUE TITLE
World Eye is a WMD

### ISSUE THREAD

**Issue by Drazuam** [Ellpeck/NaturesAura#195]
With the current code for the world eye tile (unless I'm reading it wrong...), it will eventually drain all the aura out of an area and cause a massive crater to form from the explosive effects of aura drain.  Unfortunately, this did happen to me on a server I was playing on, leaving a giant crater behind.  For what it's worth, I was based within the spawn chunks - I was using a world eye, as spawn chunks will not tick plant growth.  Here is the result of being offline for around a week:

![unknown](https://user-images.githubusercontent.com/1339554/108031513-d4019700-6fe5-11eb-979e-8a68c8e3df9d.png)

This could have devastating results for griefing - all you'd have to do is place a world eye anywhere near the target's base, then wait a week.  I'd recommend doing a check on the local aura on tile entity tick, and unloading the chunks if the local aura is below some threshold (maybe stop at plant decay?  Breathless is also pretty rough).  This will be a little more forgiving on players who are on a server as well - a little mix up in your aura generation probably shouldn't be punished with total base loss.

**Comment by Ellpeck** [comment]
This is.. the point of the mod's power system.

**Comment by Drazuam** [comment]
I'm not arguing that it's not the point - I'm saying that the punishment here is too extreme, to the point of being a balance issue.  A single block can destroy your base (or somebody else's!) if you don't understand how it works.

Most importantly, with any other aura consumer you will get (almost immediate) negative feedback from your actions, resulting in you quickly learning that you need to address aura drain.  With the world eye, you don't get to experience that feedback - you just log back in to a crater.
