### ISSUE TITLE
TwerkItMeal doesn't grow Ancient Sapling

### ISSUE THREAD

**Issue by Wxrlds** [Ellpeck/NaturesAura#197]
[TwerkItMeal](https://www.curseforge.com/minecraft/mc-mods/twerkitmeal) doesn't apply the Bonemeal effect on the Ancient Sapling when you crouch. TIM is configured to only work on Saplings which the Ancient Sapling is. Not sure if this is an issue of Natures Aura or TIM so reporting this to both.
Minecraft: 1.16.5
Mod Versions:
-NaturesAura-34.0
-TwerkItMeal-1.3.7
Link to TwerkItMeals issue: https://github.com/KyleBCox/TwerkItMeal/issues/7

**Comment by KyleBCox** [comment]
this will likely be caused by Natures Aura not implementing the IGrowable/SaplingBlock interface/class on the ancient sapling

**Comment by Ellpeck** [comment]
It [does](https://github.com/Ellpeck/NaturesAura/blob/main/src/main/java/de/ellpeck/naturesaura/blocks/BlockAncientSapling.java#L23).

**Comment by KyleBCox** [comment]
heckin oof, will take a look
