### ISSUE TITLE
[Feature Request] Leaves infestion progress with WAILA

### ISSUE THREAD

**Issue by TimGoll** [Ellpeck/NaturesAura#2]
show the progress in WAILA because (especially as a newbie) it is hard to determine when the leave is finished

**Comment by TimGoll** [comment]
Yep this would be a good alternative! Maybe add some "berries" in the leaves texture (like with the oreberries mod) when it is finished.

As a side note: I love your mod, it's really fun!

**Comment by Quarris** [comment]
May be a little bit of an effort (= balanced) but maybe have gold leaf particles drop occasionally from the bottom of the leaves?

**Comment by TimGoll** [comment]
wow, you're fast!
