### ISSUE TITLE
Shooting Mark Crashes Server with Tridents

### ISSUE THREAD

**Issue by Allyraya** [Ellpeck/NaturesAura#201]
When attempting to use the Shooting Mark with Tridents as the projectile fired from a dispenser, the server crashes with a StackOverflow error.

**Comment by Ellpeck** [comment]
Please provide the crash report.

**Comment by Allyraya** [comment]
[crash-2021-03-22_13.24.44-client.txt](https://github.com/Ellpeck/NaturesAura/files/6184275/crash-2021-03-22_13.24.44-client.txt)
[2021-03-22-2.log.gz](https://github.com/Ellpeck/NaturesAura/files/6184278/2021-03-22-2.log.gz)

**Comment by Allyraya** [comment]
The log should show it I think, but I copied my latest crash log as well.

**Comment by Ellpeck** [comment]
The crash report is unrelated to Nature's Aura. The crash is most likely caused by `simplyjetpacks`.

**Comment by Allyraya** [comment]
Apologies, but I am not using a simplyjetpacks jetpack.
