### ISSUE TITLE
[Suggestion]Radiation Cleaner

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [Ellpeck/NaturesAura#204]
A new "end-game" item which can clear Mekanism Radiation. 

Ideea come from here.
https://github.com/NillerMedDild/Enigmatica6/issues/1925

This is my ideea for crafting recipe.

x4 Fully charged Aura Trove + x4 Ingots of the skies + Spirit of Calling.

**Comment by Ellpeck** [comment]
I don't want any cross-mod compatibility that *requires* the other mod to be present in order to function or exist, sorry.
