### ISSUE TITLE
Request to be able to change the colour of aura balls.

### ISSUE THREAD

**Issue by ArkenorOakshadow** [Ellpeck/NaturesAura#205]
Would it be at all possible to have a setting to change the colour of all those little yellow balls that appear everywhere? My eyes are not terribly good, and I am constantly mistaking them for xp balls. Or maybe making them less ball-like would work.

**Comment by Ellpeck** [comment]
The color of the aura particles is based on the grass color, so it's not really possible to change it universally. You can always install a resource pack that changes the texture though (maybe to a star or something), and that way, they'll look different even with the same color!
