### ISSUE TITLE
Nature's Aura not compatible with optifine G7 or G8.

### ISSUE THREAD

**Issue by QPCrummer** [Ellpeck/NaturesAura#206]
[crash-2021-04-22_08.59.37-fml.txt](https://github.com/Ellpeck/NaturesAura/files/6358388/crash-2021-04-22_08.59.37-fml.txt)
![Capture](https://user-images.githubusercontent.com/66036033/115718627-49bd1280-a349-11eb-8f61-cd11d47ba6ce.PNG)

**Comment by Ellpeck** [comment]
This doesn't look to be a Nature's Aura issue.
