### ISSUE TITLE
Imperceptible Builder Doesn't

### ISSUE THREAD

**Issue by kitsu** [Ellpeck/NaturesAura#207]
I thought I had a clever idea: automate gold powder placement for the ritual of the forest using the imperceptible builder.  
I did all the crafting and set the whole thing up and it started working! Except it didn't actually do anything... A sound like dirt breaking plays (emanating from the target blocks) but no powder is used and no aura is consumed.

I did a few simple tests - tried changing the builder's height relative to the target blocks, tried alternative target and placement blocks (tried dirt on stone brick). Nothing works?!

The hopper enhancer and other blocks and effects are all working fine, just the builder is broken.

Nature's Aura 34.2 Minecraft 1.16.5 Forge 36.1.3

**Comment by Ellpeck** [comment]
Did you add the `[Minecraft]` fake player to the allies list in your chunk protection mod (or enable fake player interaction some way)?

**Comment by kitsu** [comment]
I don't have chunk protection. No FTB anything. This is single player running locally.

**Comment by Ellpeck** [comment]
Are you within the range of spawn protection, perhaps?

**Comment by kitsu** [comment]
No, I'm at least a dozen chunks from spawn.
I also did _not_ see any log output (errors):
```
[08:31:47] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] kitsu_eb has made the advancement [Plop Plop Placement]
[08:31:47] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 6778 advancements
[08:44:33] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@14bedc42
[08:49:52] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
```

Seems like MultiMC doesn't provide a way to export the modlist, so here are some screen shots (sorry):
![image](https://user-images.githubusercontent.com/2218853/116820251-d7a6b380-ab28-11eb-84be-874451deb0d8.png)
![image](https://user-images.githubusercontent.com/2218853/116820267-f147fb00-ab28-11eb-98fb-3f4f07a3b3c4.png)

**Comment by Ellpeck** [comment]
Please see if you can reproduce the issue with just Nature's Aura (and Patchouli) installed. If you can't, please try to figure out which mod might be causing the issue.

**Comment by kitsu** [comment]
Ok, duh:  
I was about half way down the mod list, testing by functional groups (client side, utility, Vaskii, etc.) when I realized what it was:
Added MineColonies and Structurize, load, flip lever, it still works - establish colony right next to test rig and immediate failure with same symptoms as above.

Thanks for your time, hopefully I can find the relevant setting in the MineColonies config.

**Comment by kitsu** [comment]
Note for future sufferers: In the town hall permissions tab there is a second page for types of permission - allowing "neutral" to place blocks (and break, pickup, and drop for good measure) allows this to work.
