### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by Fortist** [Ellpeck/NaturesAura#21]
Sapling, Logs, Planks, Leaves

**Comment by Ellpeck** [comment]
Not happening, sorry. OreDict-based recipes are super annoying since the json recipe change and, because of that, if I were to oredict ancient woods, recipes like ancient rods wouldn't work anymore.

**Comment by hron84** [comment]
But your custom wood and planks are added to oreDict? Can we use them in other (non-NaturesAura) recipes, like chests or piston?
