### ISSUE TITLE
Ritual of The Forrest consuming surrounding trees.

### ISSUE THREAD

**Issue by DEX47** [Ellpeck/NaturesAura#211]
Ritual of The Forrest consuming surrounding trees when the ritual tree grows. It also consumes the ground beneath the tree.

Minecraft 1.16.5
Forge 36.1.16
Nature's Aura 34.2

![2021-06-04_13 38 37](https://user-images.githubusercontent.com/8147134/120848378-58970780-c53a-11eb-9fa5-1f3682e86341.png)
![2021-06-04_13 38 53](https://user-images.githubusercontent.com/8147134/120848389-5af96180-c53a-11eb-8fa5-d99b3ea8ea33.png)

**Comment by Ellpeck** [comment]
There's no way to stop this from happening, as leaves don't know which tree they are actually connected to. Just remove possible connections between the ritual tree and any other trees.

**Comment by DEX47** [comment]
Are you able to isolate the selection to exclude wood planks, slabs, and non-wood objects? My original workshop for your mod was on my roof. It ate me house ^_^

**Comment by Ellpeck** [comment]
It only removes logs and leaves, so there must be some mod in your modpack that (hopefully accidentally) tags random stuff as logs or leaves.
