### ISSUE TITLE
Ancient Wood Rod recipe missing

### ISSUE THREAD

**Issue by DEX47** [Ellpeck/NaturesAura#213]
Ancient Wood Rod recipe is not registering. Attempted to work around the issue with polymorph. That was unsuccessful as was an attempt to create a datapack specifily for the Ancient Wood Rod recipe. Appears to be a mod conflict. Are their any know conflicts that result in this behavior?

Minecraft 1.16.5
Forge 36.1.16
Nature's Aura 34.2

**Comment by Ellpeck** [comment]
The ancient wood rod is made from two ancient wood **slabs** on top of each other. If that doesn't work, please try to remove mods to figure out which mod is causing this issue.

**Comment by DEX47** [comment]
Working on mod isolation. This will take some time.

**Comment by Ellpeck** [comment]
This issue has been stale for a while, so I'm closing it. If this issue persists, please reopen the issue.
