### ISSUE TITLE
Doubling the growth powder on the server.

### ISSUE THREAD

**Issue by GnomTocha** [Ellpeck/NaturesAura#214]
1. Placed a stack of Powder of steady growth.
2. Collect the powder.
3. At the exit we get 2 stacks.
NaturesAura-34.2
forge-1.16.5-36.1.23

**Comment by Ellpeck** [comment]
Cannot reproduce. Please try to reproduce this issue without any other mods installed.

**Comment by Ellpeck** [comment]
This issue has been stale for a while, so I'm closing it. If this issue persists, please reopen the issue.
