### ISSUE TITLE
Lamps crashing in worldgen with rftools dim

### ISSUE THREAD

**Issue by criscky** [Ellpeck/NaturesAura#215]
https://paste.gg/p/anonymous/ddac6034e52642b8ac8082a7ff71b0ed/files/97c3d523825c4bf0a527aacbd69cd000/raw

Sorry if i cannot provide more info, this crash was given to me in the MCE discord server
for what i was told they made a dim (i dont know which parts they used) and when they enter the dim the game crashed
I'm not sure if this is a conflict between nature's aura worldgen and rftools dim
i can try reproduce this later if you want

**Comment by Ellpeck** [comment]
1.12 is not supported anymore.
