### ISSUE TITLE
A bug deleted my book and I crafted a new one but it deleted all of my research

### ISSUE THREAD

**Issue by MrTubzy456** [Ellpeck/NaturesAura#219]
Pretty much the title. I had a bug delete the book and I crafted a new one and everything was deleted from the book. I can't look at anything at all. I can't look at the encyclopedia, anything at all. I want to continue playing with the mod but as it is right now I can't do a thing. 

Thanks in advance for your help. Here's a screenshot of the book: https://imgur.com/a/zomBQQD

**Comment by Ellpeck** [comment]
The research in the book is linked to vanilla advancements, so you can [use commands](https://minecraft.fandom.com/wiki/Commands/advancement) to add/remove advancement progress to edit the progress in the book.

If this issue happens again, please report it to the [Patchouli](https://github.com/VazkiiMods/Patchouli) devs, as they are the ones who maintain the manual.
