### ISSUE TITLE
Dedicated(?) Server Crash related to "nearby animals mate" effect

### ISSUE THREAD

**Issue by Birgliss** [Ellpeck/NaturesAura#22]
using nature's aura b6, and forge 2783
[crashlog here](https://gist.github.com/Birgliss/ac3c8b1f318c50f7cd4f0a6c9cda1d79)
[modlist here](http://modlister.com/user/Cavariel/Millenia)

currently i'm trying to reproduce this in singleplayer, but i'm having trouble? 
the logs suggest it's related to the animals mating in areas of excess aura, but in singleplayer it didn't cause a crash.
however, as far as i know, to reproduce on a server, all you need to do is have a pen of animals, and get your aura high enough for them to start mating each other.

please let me know if there are any more details i can supply.
i'll let you know if i find out anything else.

**Comment by Ellpeck** [comment]
This is a serverside only issue. You can disable the animal effect in the config for the time being, though.
