### ISSUE TITLE
The Environmental Ocular's Aura Imbalance icons don't update when near Effect Powder

### ISSUE THREAD

**Issue by Jeuvke** [Ellpeck/NaturesAura#222]
Placing Effect Powder in the world doesn't add or remove the red X over the corresponding Aura Imbalance icon shown by the Environmental Ocular. This also affects Nature's Starlight's Starry Skies effect.

**Comment by Ellpeck** [comment]
Hmm, I can't reproduce this with just Nature's Aura and Patchouli installed. Can you try to reproduce it and, if it doesn't happen, see what mod might be causing it? Thanks!

**Comment by Ellpeck** [comment]
Oh. It's been so long since I did this fix that I forgot, but this has already been fixed [in dev](https://github.com/Ellpeck/NaturesAura/commit/204007cfd768490a364d9251115a7d43a2379f28) a long while ago. Today's update should release this fix!
