### ISSUE TITLE
Failed to get color name for 1 spring naturesaura:spring

### ISSUE THREAD

**Issue by aburone** [Ellpeck/NaturesAura#226]
On logs, while game is loading
https://hastebin.com/iqotuxixak.rb

**Comment by Ellpeck** [comment]
That haste seems to have been deleted somehow. Also, hastebin's link seems to have been changed, but even putting https://www.toptal.com/developers/hastebin/iqotuxixak.rb doesn't yield a non-empty result. Meh.

Please resubmit this issue using a service that didn't just *decide to become wonky*, like GitHub Gist or Pastebin. Thanks!
