### ISSUE TITLE
[1.16.5] Tree ritual only work once

### ISSUE THREAD

**Issue by joe-vettek** [Ellpeck/NaturesAura#228]
It seems that tree ritual can only be done once in the archive, and it doesn't respond the second time.

**Comment by joe-vettek** [comment]
34.3 does not work properly, but 34.2 seems to work.

**Comment by joe-vettek** [comment]
<item:naturesaura:aura_bottle>.withTag({"rpgloot.randomize": 0 as byte, stored_type: "naturesaura:overworld" as string}) 
<item:naturesaura:aura_bottle>.withTag({stored_type: "naturesaura:overworld" as string}) 

The aura bottle nbt in 34.3 is the first one, and the second one is a similar item in 34.2.After spending several hours, I finally found out that it was a problem with the nbt of aura bottle.

**Comment by joe-vettek** [comment]
![str](https://user-images.githubusercontent.com/82761814/144566350-3fc375e7-ec17-488a-981a-61ba54c6bf20.png)

**Comment by Ellpeck** [comment]
While this is, of course, an issue with the recipe type comparisons, I don't necessarily think that this is my issue to fix. I just use Forge's default NBT recipes, which (apparently) compare based on all factors, not just the ones you provide. 

How did the additional NBT tag get onto the item? If you just created it normally, it seems *very wrong* for another mod to add an NBT tag that looks to just mean "this item was *not* randomized".
