### ISSUE TITLE
[Feature Request 1.16] Bypass progression in the guide book

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/NaturesAura#229]
E6E has moved some things around, such as bringing the altar of birthing forward in terms of the intended NA progression. 

This results some entries not being accessible in the patchouli manual when they'd be useful.

Could you consider adding a config option that simply opens the book up completely, regardless of other progression?

**Comment by Ellpeck** [comment]
Patchouli already has a config option like that.

**Comment by MuteTiefling** [comment]
ah, cool. I knew PNC had one for its own book so I didn't think to check patchouli in general. Thanks!
