### ISSUE TITLE
JEI did not show changes when recipes are changed via Crafttweaker

### ISSUE THREAD

**Issue by joe-vettek** [Ellpeck/NaturesAura#230]
<recipetype:naturesaura:animal_spawner>.addJSONRecipe("test154fhg", {
    "type": "naturesaura:animal_spawner",
    "ingredients": [{
            "item": "minecraft:honey_block"
        }
    ],
    "entity": "productivebees:creeper_bee",
    "aura": 1,
    "time": 1
});

**Comment by joe-vettek** [comment]
This recipe is effective in the game, so I think it is a problem with the JEI plug-in.

**Comment by Ellpeck** [comment]
That's.. weird. Would you mind trying to change a recipe with KubeJS instead of CraftTweaker? You won't have to switch to it permanently, I just want to know whether it's a CraftTweaker-specific issue.

Also note that you can use a datapack to change recipes, if you want.

**Comment by joe-vettek** [comment]
Datapack also can't solve the problem.I had tested it too.
And sorry I don't have time to learn about Kubejs now until the next month.

**Comment by joe-vettek** [comment]
Maybe I didn't express it correctly.I tested later and found that the recipe can be found by clicking on the item, but not by directly viewing the ritual-related content.

**Comment by Ellpeck** [comment]
This should have been fixed by a change during the 1.18 port.
