### ISSUE TITLE
advancement data format changed, causing advancements to get awarded erroneously

### ISSUE THREAD

**Issue by esotericist** [Ellpeck/NaturesAura#231]
in the 1.18 version of nature's aura, simply obtaining an item will award a large number of advancements that should not yet be awarded. for instance:
![image](https://user-images.githubusercontent.com/1569754/147002986-1bc9e771-fdd6-4292-8408-eedb42837e81.png)

this particular example was done by collecting an iron helmet (which is why suit up is in the list), but it would work with any item. this is due to a change in the json data on the vanilla minecraft side:
 `"item": "minecraft:polished_granite",` to ` "items": ["minecraft:polished_granite"],`

a diff of the changes in the timeframe as described in the history of the minecraft wiki:
https://minecraft.fandom.com/wiki/Advancement/JSON_format?type=revision&diff=1952481&oldid=1908997

the supplementaries dev has already integrated that change in the commit here, if that's helpful (but honestly, as far as i can tell it's just the above change from item entry to items array)
https://github.com/MehVahdJukaar/Supplementaries/commit/e7963136441d873c401bd08493fc7b30b0561b0f

the most obnoxious thing about this is that the old format doesn't produce an obvious error, it just silently fails to be a valid condition.

**Comment by Ellpeck** [comment]
Wow, that is super annoying. Thanks for the research, though!

**Comment by esotericist** [comment]
i have to credit mehvahdjukaar with actually learning it was a deliberate mojang change. i spent a few hours chasing down "why the hell advancements" last night and it would have taken me a lot longer to realize why without the pointer.
