### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Ashur420** [Ellpeck/NaturesAura#233]
Nature's Aura is crashing on startup.

https://pastebin.com/NZ4799iV

**Comment by Ellpeck** [comment]
At first glance, this looks like a Quark issue.

**Comment by Ashur420** [comment]
Thanks for the quick reply!  It loads fine by itself.  Doesn't seem to be quark as it still crashes without quark installed.  Might be an error with flywheel lib for Create.  Sorry I don't know anything about java!

https://pastebin.com/GH223aHT
