### ISSUE TITLE
Book of Natural Aura - Missing Steps

### ISSUE THREAD

**Issue by Rayskiz** [Ellpeck/NaturesAura#234]
I've come across some missing steps that prevent me from advancing further.  Under the section for The Ritual of the Forest, I am able to build the alter but the pages that show recipes for the tokens are not showing up.  It is the same with the steps after The Natural Alter section.  I can see the way to build it but after that the pages are blank.

I have tested this with various Mods as well as a fresh install on it's own.

Natute's Aura v35.2 & v35.1
Patchouli v1.18.1-61
Minecraft 1.18.1
Forge 39.0.8

**Comment by esotericist** [comment]
i also experience this, with patchouli 1.18.1-63, nature's aura 35.2, and forge 1.18.1-39.0.8.
