### ISSUE TITLE
[1.18.1] Nature's Aura is tanking TPS on server. (spark profile link included.)

### ISSUE THREAD

**Issue by Gbergz** [Ellpeck/NaturesAura#235]
**Title ^**

### Info
Recently our server has been taking hits with TPS lag. Did a Spark Profile and it looks like Nature's Aura is taking up 40% of the entire server. Down to almost 2 tps.

### Versions:
Forge: 39.0.9
Minecraft: 1.18.1
Nature's Aura: 35.3
Patchouli: 1.18.1-63

**Spark Profile Link:** (Click Eye (all) on the right.)
https://spark.lucko.me/4NH9jdAqfu

(de.ellpeck.naturesaura.Helper.getLoadedChunk() is currently taking up 41.58%

**Comment by Gbergz** [comment]
Server now proceeded to crash. (erverHangWatchdog detected that a single server tick took 180.00 seconds (should be max 0.05))
https://gist.github.com/Gbergz/8f74ad9ebf1b801d70e2b5c98005574c

**Comment by Ellpeck** [comment]
absolutely *screaming* at the fact that the thing that is taking TPS is a method that I added this comment to a long while back:
```
// DO NOT EDIT PLEASE FOR THE LOVE OF GOD
// This is very finicky and easily causes the game to hang for some reason
```

**Comment by Gbergz** [comment]
Hm, so is there anything on my side I could do?

**Comment by Ellpeck** [comment]
Wait! 

That's pretty much it though, sadly. Probably gonna do an update tonight or tomorrow. We'll see.

**Comment by Ellpeck** [comment]
Would you mind trying again with [this version](https://ci.ellpeck.de/job/NaturesAura/job/main/110/artifact/build/libs/NaturesAura-35.3.110.jar)? It might be a lot better, but it might also be unchanged. Yay?

**Comment by Gbergz** [comment]
Didn't work with that one, same lag.
New profile: https://spark.lucko.me/ccwGXXJVAl

**Comment by Barteks2x** [comment]
if you want to get loaded chunk, I think that would be the way to do it (completely untested, but that's based on my understanding of how the system works):
```java
    public static ChunkAccess getLoadedChunk(LevelAccessor level, int x, int z) {
        if (level.getChunkSource() instanceof ServerChunkCache cache) {
            ChunkHolder holder = cache.getVisibleChunkIfPresent(x, z);
            var future = holder.getFullChunkFuture();
            return future.isDone() ? future.getNow(ChunkHolder.UNLOADED_CHUNK).left().orElse(null) : null;
        }
        return level.getChunk(x, z, ChunkStatus.FULL, false);
    }
```

**Comment by ohnx** [comment]
It looks like you've already identified the code causing problems, but if you wanted more data, I am also running into this issue on a server that I run. Issue appears as high jitter in TPS (regular TPS is fine; some ticks occasionally take a long time). Here's a spark profile: https://spark.lucko.me/CH6JN8tryN

I'm running the same versions of everything as the original poster.

**Comment by Ellpeck** [comment]
What abooouuuut [this version](https://ci.ellpeck.de/job/NaturesAura/job/main/111/artifact/build/libs/NaturesAura-35.3.111.jar)? Seems to be pretty good from my brief testing. Fingers crossed.

**Comment by ohnx** [comment]
Seems to have helped, thanks! New profiler results show that Nature's Aura is no longer causing the TPS jitter (although it seems that another mod I run is running into the same issue): https://spark.lucko.me/XKl7UbT7MW
