### ISSUE TITLE
Canopy Diminisher does not recognize modded large oak tree variants

### ISSUE THREAD

**Issue by NillerMedDild** [Ellpeck/NaturesAura#236]
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/3952

Not sure how much you can do about this tbh, but... halp 😅

**Comment by Ellpeck** [comment]
Nothing I can do about this without adding explicit compatibility for those mods, which I'm not really willing to do, as there's a lot of different mods that add larger oak trees. Sorry!

**Comment by NillerMedDild** [comment]
Okay 😞
