### ISSUE TITLE
Advancement unlock upon entering new world

### ISSUE THREAD

**Issue by Dissgruntled** [Ellpeck/NaturesAura#24]
NaturesAura-r10
Auraddons-1.5-NAr10
Forge 1.12.2 - 14.23.5.2810

Whenever I enter a new world, the advancement "Luscious Surroundings" (Create enough aura to cause positive imbalance effects) unlocks immediately.

**Comment by Ellpeck** [comment]
This has already been fixed in dev, but thanks for reporting! :)
