### ISSUE TITLE
Breathlessness Is Constantly Hurting Me Even With High Aura

### ISSUE THREAD

**Issue by Brotuulaan** [Ellpeck/NaturesAura#241]
I have several swamp homis set up around my base because the aura is apparently being drained by something, so I started suffocating constantly. It was especially bad in my basement, but I definitely had nothing set up down there. I ended up adding a second down there because it was so bad and the one up top wasn't enough.

But since I updated the pack I'm playing (ATM6), it's apparently changed something so no matter how high my aura is, I'm still choking to death. This is stupid, this breaks the game, and this makes the entire pack unenjoyable because I can't do anything since I'm dying just standing there. The book says that happens when the aura gets too low, but I'm choking even with the aura about 1/5 above the middle line (balanced, I guess?).

I can't find any way to deactivate breathlessness bc I don't see a config file in the installation folder. How the hell am I supposed to play if this feature is killing me when it's not supposed to be doing anything at all?!

**Comment by Ellpeck** [comment]
Breathlessness has a very high radius (up to 100 blocks), so the area that is causing it is probably a little ways away.

Aura is only drained by things from the mod, so you must have something around that drains it. Common offenders are the infinite spring block and the ender crates.

You can also disable breathlessness in the config file.

**Comment by Brotuulaan** [comment]
Thanks for replying. Oh, I'd forgotten the infinite spring is from this mod. I do have one of those set up and it just sits and supplies y system via an ender tank. That would also explain why the drain was worse in my basement since that's where it used to sit before I moved it.

Do you mean that breathlessness in a low-aura area can still kill you while you're in a high-aura area, like low aura areas overpower adjacent high aura areas?

**Comment by Ellpeck** [comment]
Yes! 

The more aura a high aura area has, the more it will spread and try to balance out low aura areas around it. This effect is most effective when the amount of aura exceeds the Environmental Eye's display range.
