### ISSUE TITLE
Incompatibility with other mod

### ISSUE THREAD

**Issue by Selsus74** [Ellpeck/NaturesAura#243]
As i was installing a bunch of mods, I stumbled over an Incompatibility of your mod "Nature´s Aura" with the mod/s "Nuclear Science" and probably but not necessarily it´s dependency "Electrodynamics" . Here are their CurseForge Links for investigating, tho i do not await a fix for this issue. https://www.curseforge.com/minecraft/mc-mods/nuclear-science , https://www.curseforge.com/minecraft/mc-mods/electrodynamics . It seems to be one of those weird Mixin-ish things that break the ´Multiblockmaker` , giving the IndexOutOfBoundsExeption. Just wanted to inform about this incompatibility so others won´t have to "trial and error" for 300 mods like i did.

**Comment by Ellpeck** [comment]
Hi, do you have a crash report you can share?

**Comment by Ellpeck** [comment]
This has already been fixed in https://github.com/Ellpeck/NaturesAura/commit/f5428adbc67182e58db1fca3f2a374cb0a3f2d1a. I doubt there's a backport coming for this in the near future, though.
