### ISSUE TITLE
Lag on server

### ISSUE THREAD

**Issue by Gogo08190** [Ellpeck/NaturesAura#246]
Lag spike due to Natures Aura can you fix that ?
![image](https://user-images.githubusercontent.com/41335079/160825493-f9b1f515-2547-4d42-b006-3b311939d31f.png)

Spark profiler : https://spark.lucko.me/HLP47I7PEL

**Comment by Ellpeck** [comment]
This just looks like there is an area in the world somewhere with a ridiculously high amount of aura in it. Unfortunately, Minecraft 1.16 is generally not supported anymore unless it's a very game-breaking bug. 

Can you try to scout out the area in the world that is causing these issues, turn on the "debug world" config option in the Nature's Aura config, press F3 while in creative mode, and observe how many aura spots are around? A screenshot would be great!

**Comment by Ellpeck** [comment]
Yea, that is just a very large amount of aura. I recommend employing an Aura Detector to stop your aura generation when there is enough in the area. If you want to clear this up, you can use the `/naaura reset` command, which will reset the aura in a radius of 35 blocks around the location you're executing the command.

**Comment by Gogo08190** [comment]
Can I reset all aura area with a file ? A file who sotck all the data from the aura zones?

**Comment by Ellpeck** [comment]
No, aura is stored in each chunk.
