### ISSUE TITLE
Larger aura cache 

### ISSUE THREAD

**Issue by CraftingMom** [Ellpeck/NaturesAura#247]
I need to re-enchant all my gear to replace nature's mending with vanilla mending because the aura cache doesn't hold enough to repair all my armor. 

It also needs to have a way to recharge the nature's altar with xp from the player and with bottled sunlight.

**Comment by Ellpeck** [comment]
There's already the Aura Trove which has a much bigger storage. Are you using that?

**Comment by CraftingMom** [comment]
I just learned about it because the mod keeps everything locked. So there was no way to know that would eventually be available. Meanwhile, I couldn't get that unlocked because of needing to keep use up aura to fix things. 

Looks like a good mod when everything is unlocked, but the lack of transparency in game is frustrating.
