### ISSUE TITLE
How to unlock rose of oblivion?

### ISSUE THREAD

**Issue by CraftingMom** [Ellpeck/NaturesAura#248]
I've done every achievement except the ones that require the rose of oblivion. The ender dragon has been killed 5 times on the server, once by me. No roses generated.

**Comment by Ellpeck** [comment]
What version of the mod are you on? There was a bug fix recently that allowed them to spawn again, so that might already be the fix you're looking for.

**Comment by CraftingMom** [comment]
35.4 ty for already fixing it.

**Comment by Ellpeck** [comment]
This issue was fixed in 35.5 so you'll just have to update!
