### ISSUE TITLE
Late Game Performance Issues

### ISSUE THREAD

**Issue by sehaubold** [Ellpeck/NaturesAura#252]
**Problem**: Consistent server lag in the (relative) late game
**Symptoms**: Failed block breaks, rubber banding, stuttering, all on local host
**Potential fix**: Somehow making the chunk update more efficient
**Viable workaround**: Making the aura chunk update an adjustable frequency - I think CC Tweaked has options like this.
**Desc**: We have a server of about 10-12 people, with 3-6 on simultaneously at a given point in time. Lately, we have been having some consistent server lag, which we thought was due to Create or Mekanism, but when we pulled the server report (below) Natures aura outstrips the second highest performance drain by ~4x. For reference, Mekanism was 2nd place at 8%. Can provide additional info as needed.

We've really enjoyed this mod and it is the source of my power generation personally, so it hurts to consider potentially resetting or even removing it from our pack. If this was a problem from the beginning, we were unable to tell, so we assumed it was due to the accumulation of aura or the generation of aura. We found this was still an issue after shutting off our aura generators and aura forges.

![Capture](https://user-images.githubusercontent.com/39908910/169455377-35a69a7a-ab39-461a-a99e-876ef12aef63.PNG)

**Comment by Ellpeck** [comment]
Hi, thanks for the issue report!

What version of the mod are you on?

It'd be great if you could share the full spark profile.

**Comment by sehaubold** [comment]
Sure thing! I am currently on version 36(?) NaturesAura-36.0.jar as part of the All The Mods 7 pack (ver. 3.18)


https://spark.lucko.me/eDtLS8alYU

**Comment by Ellpeck** [comment]
I made some changes to the way the amounts of aura are calculated, and more values should be cached now, leading to less computation time required. 

Is it possible for you to test the performance with [this debug build](https://ci.ellpeck.de/job/NaturesAura/job/main/123/artifact/build/libs/NaturesAura-36.0.123.jar)? If you can, it'd be great if you could do another spark profile, as well as check to see if all of the mod's features still work as expected, as there is a chance that the caches might be invalidated incorrectly, causing aura values to be wrong.

**Comment by sehaubold** [comment]
I'll see if i can get a concurrent build running locally once im at the host PC, Thanks for the quick turnaround!

**Comment by sehaubold** [comment]
just ran the Spark profiler - From 32% to 19% in one go! wowzers.
below is the profile

https://spark.lucko.me/W69M3jxxlh

**Comment by Ellpeck** [comment]
There are still some smaller changes I can do to increase the performance!

If you don't mind doing some additional testing for me, would you mind joining [the Discord server](https://ellpeck.de/discord) and DMing ell from there?

**Comment by Ellpeck** [comment]
This has been taken care of in the Discord and should now be much improved!
