### ISSUE TITLE
[1.18] [Bug?] Explosions caused by an extreme lack of aura bypass chunk protection 

### ISSUE THREAD

**Issue by Iris-xii** [Ellpeck/NaturesAura#255]
Versions:
NaturesAura-36.2
ftb-chunks-forge-1802.3.6-build.145
Forge 40.1.31

Explosions caused by an extreme lack of aura seem to bypass chunk protection. The behavior I expected is for them to not do that. 

I know this issue is fairly brief but I'm not sure what else to add, that just seems to be it. Let me know if you need any additional information.

**Comment by Ellpeck** [comment]
Honestly divided on whether this makes sense or not. I'll leave this open for now, but I'll have to think about this!
