### ISSUE TITLE
[1.18.2] Sometimes upon starting server it crashes with ("Mod loading error has occurred").

### ISSUE THREAD

**Issue by Gbergz** [Ellpeck/NaturesAura#258]
Title ^
This doesn't happen every time but it does once in awhile.

## Versions
Minecraft: 1.18.2
Forge: 40.1.48
Nature's Aura: 36.2
Patchouli: v69

## Crash Report
https://gist.github.com/Gbergz/c343b28cf1b915999b012c30e0241ac8

**-** Gbergz

**Comment by Ellpeck** [comment]
This looks like an issue caused by the Balm mod.
