### ISSUE TITLE
Environmental Eye not being produced in Ritual of the Forest

### ISSUE THREAD

**Issue by archonsd** [Ellpeck/NaturesAura#259]
Is the recipe in the latest Natures Aura right?  My ritual of the forest worked for a few things.  I put the spider's eye north, a gold leaf east and west, a gold ingot south, and a normal oak sapling in the middle.  I bone meal'd the sapling into a tree one time and got a large oak.. waited..  nothing for 10 minutes.  I chopped it down, left the parts in the ritual, put another sapling in the middle, bone meal'd that and a normal sized oak appeared..  but the ritual doesn't appear to be doing anything..  Is there a trigger I'm missing, or maybe the recipe is not correct in the book?

Can the level of aura in the environment affect the Ritual of the Forest?  I don't yet have a way to see the level of aura.  I've got an aura generating tree nearby and it isn't withering or anything..  it's been in the world for two physical days now..  so it really should be well stocked..  I just can't see the aura level to be sure.

**Comment by Ellpeck** [comment]
Hi! Did you put down the gold powder around the sapling?

**Comment by archonsd** [comment]
Damnit..  lol..  I forgot.  The book leaves that out so I regularly forget to do it..  LOL

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by archonsd** [comment]
Confirmed.  I had to lay down the gold powder, remove the grown tree, place down a new sapling, and in my case bone meal it to grow.
