### ISSUE TITLE
[Suggestion] Change wording in config to avoid confusion

### ISSUE THREAD

**Issue by TheInfamousAlk** [Ellpeck/NaturesAura#260]
In the .toml config file, specifically in the auraTypeOverrides line, the documentation directly above says how to format it, but does not mention that you need to put quotation marks around the entries (also that the entries need to be separated by a comma). I spent quite a while troubleshooting why my config change was causing it to fail reading the config file. I eventually stumbled on an issue in the github unrelated to this, where someone gave an example of a config entry that was formatted properly, which let me resolve the issue. 

I propose that a note be added in any comment that lists formatting, explaining that quotation marks and commas need to be used in the formatting. I will post the original vs my suggested updated segment from the config (applicable to all parts of the config where formatting is discussed):

Original:

#Additional dimensions that map to Aura types that should be present in them. This is useful if you have a modpack with custom dimensions that should have Aura act similarly to an existing dimension in them. Each entry needs to be formatted as dimension_name->aura_type, where aura_type can be any of naturesaura:overworld, naturesaura:nether and naturesaura:end.
	auraTypeOverrides = []

Updated:

#Additional dimensions that map to Aura types that should be present in them. This is useful if you have a modpack with custom dimensions that should have Aura act similarly to an existing dimension in them. Each entry needs to be formatted as "dimension_name->aura_type", where aura_type can be any of naturesaura:overworld, naturesaura:nether and naturesaura:end. Each entry must be separated by a comma.
	auraTypeOverrides = []

**Comment by Ellpeck** [comment]
This is really just a part of the [toml file format](https://toml.io/en/v1.0.0), so I don't think explicitly mentioning it in every config entry makes sense.

**Comment by TheInfamousAlk** [comment]
I would reckon that most people playing minecraft don't know the toml file format, they just open a config and change some values. The fact that formatting is suggested at all implies that the formatting suggested is complete and accurate, when it is not. Most people will have no way of knowing they need quotation marks and they would also not know to google "toml file format" when a config change doesn't work. If you write comments at all, I think they should be written for the average user who will read them, not an advanced user. I have never had to look up toml file formatting in my history of playing minecraft, and I've been hosting servers since tekkit.

**Comment by Ellpeck** [comment]
Fair enough! I'll reopen this issue for now.
