### ISSUE TITLE
NaturesAura-36.2.jar

### ISSUE THREAD

**Issue by ZamalamaDingDong** [Ellpeck/NaturesAura#263]
Hey, i want to started a modpack with this mod. but when i start up the Launcher i become this massage/crash report.

Failure message: Nature's Aura (naturesaura) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 3090 out of bounds for length 2049
	Mod Version: 36.2
	Mod Issue URL: https://github.com/Ellpeck/NaturesAura
	Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 3090 out of bounds for length 2049

can someone Help me pls. :)

**Comment by Ellpeck** [comment]
Hi, please send the full crash report or the full log file. Thanks!
