### ISSUE TITLE
[1.18.2] Nether grass blocks do not have assigned tool and do not drop anything when broken with a silktouch tool

### ISSUE THREAD

**Issue by TheRealWormbo** [Ellpeck/NaturesAura#266]
It seems the nether grass blocks do not have an assigned tool, which I assume should be the same as e.g. the tool for nylium (i.e. pickaxe). They also does not seem to drop anything when using a tool with silktouch to break them.
A look at the loot table for the block suggests a copy&paste error from grass wather than grass blocks, as it looks like it expects shears with silktouch or something like that. However, that loot table also suggests netherrack should be dropped if the tool doesn't match, which it doesn't do.

**Comment by Ellpeck** [comment]
This should be fixed together with #277!
