### ISSUE TITLE
Ancient Tree´s leaves are green

### ISSUE THREAD

**Issue by Hurainzone500** [Ellpeck/NaturesAura#268]
Hello, i´m using a resource pack and my ancient tree´s leaves are green or look like normal oak leaves of vanilla minecraft. On the world/minimap they are rendered pink instead.

Is there anyway i can fix that myself ? I´ve tried load orders but that diden´t help.
Only if i remove the resource pack the leaves are actually pink, not just on the worldmap :/

**Comment by Ellpeck** [comment]
That's weird! The resource pack might be doing something very funky. All Nature's Aura does is change the color of the Ancient Leaves from gray to pink using the same way that vanilla Minecraft does it for grass colors.

Pleas report this to the resource pack developer, as they might be better suited to fix this. Thanks!
