### ISSUE TITLE
Powder of Chastity doesn't inhibit animal breeding

### ISSUE THREAD

**Issue by VallenFrostweaver** [Ellpeck/NaturesAura#27]
Nature's Aura v:1.12.2-1.5.1
Forge: 14.23.5.2781

Used a stack of the powder, boosted the aura, chickens and cows nearby (5 blocks from effect powder) were breeding like crazy still. The book reads that the powder inhibits the breeding effect.

**Comment by Ellpeck** [comment]
![image](https://user-images.githubusercontent.com/5741138/52345558-d061cf80-2a1d-11e9-9286-f41097beeab2.png)
Cannot reproduce. Removing the powder instantly makes them breed.

**Comment by VallenFrostweaver** [comment]
I did something off with creative mode and I think it was poorly timed. The eggs hatched a bunch as I was setting it up. Sorry to bother here.
