### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by TobiDoes** [Ellpeck/NaturesAura#271]
when i go to load up a server it crashes with Nature's Aura even though the Client runs just fine i have attached Both of the lastest log and the crash report
[latest.log](https://github.com/Ellpeck/NaturesAura/files/9570577/latest.log)
[crash-2022-09-14_17.26.39-fml.txt](https://github.com/Ellpeck/NaturesAura/files/9570578/crash-2022-09-14_17.26.39-fml.txt)

**Comment by Ellpeck** [comment]
Hmm, this is a weird one. It looks like the compatibility for Curious is being loaded before Nature's Aura's items are fully set up. Can you try to reproduce this issue without any mods other than Patchouli, Nature's Aura, and Curios installed?

**Comment by TobiDoes** [comment]
i can try

**Comment by TobiDoes** [comment]
that did work but i dont know why its just crashing on the Server and not on the client side

**Comment by Ellpeck** [comment]
Hi! Please, if you can, try to figure out what mod is causing this crash by removing mods in batches to narrow down which one it could be.

**Comment by Ellpeck** [comment]
This issue has been stale for over a year, so I will close it for now. If this issue still occurs, please open a new one or comment here!
