### ISSUE TITLE
Crash interaction with pneumaticcraft repressurized drone

### ISSUE THREAD

**Issue by JustJinxed** [Ellpeck/NaturesAura#273]
I setup a drone to try to help automate the placement of items for rituals, and it seems when the drone goes to interact with a right click on the pedestal block, it causes a crash. I was able to pass this through one of the pneumaticcraft devs (desht) to see what they thought might be the cause, and they suggest to not assume the loot context builder has a LootContextParams.BLOCK_ENTITY parameter, and to maybe instead use the getOptionalParameter() method.

crashlog https://pastebin.com/HSGRYKyB

**Comment by Ellpeck** [comment]
Hi, thanks for this report! For now, you can just attach a hopper to the pedestal and interact with that instead :)

**Comment by JustJinxed** [comment]
Well, if anyone else runs into this with pneumaticcraft drones, using the "export to inventory" as opposed to the "right click" widget, seem to work without any negative side effects. Save em some hoppers 😄
