### ISSUE TITLE
Powder of fertility does not work

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#274]
Animals ignore powder of fertility even with 3/4 of aura and only 2 animals in the same chunk.

![2022-09-16_17 46 39](https://user-images.githubusercontent.com/96169906/190654438-5da41523-f98c-4f4d-a736-00dcea946f7b.png)

**Comment by Ellpeck** [comment]
How much powder do you have in that stack? The more there is, the bigger the range; you can check with the Mystical Magnifier.

Also, 3/4 of the bar isn't necessarily that much. That's barely enough to get the plant boost effect, so I don't think it's quite enough for the animal breeding effect.

**Comment by uhloin** [comment]
As you can see on the screenshot stack size = 8 and distance to sheeps = 2.
Article "Increase of Fertility" in Patchouli sets requirement 2/3 for Powder of Fertility, and I have 3/4 > 2/3 (aura bar is at left-bottom part of screen).

**Comment by Ellpeck** [comment]
Yes, but the lower the aura, the lower the chance that it will actually happen, as with all other effects. Have you tried it with more aura in the area?

**Comment by Ellpeck** [comment]
Yay! I'm glad this was an easy fix. Enjoy :)
