### ISSUE TITLE
Armorer's Aid, Corporeal eye, Golden Stone Bricks

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#277]
1. It is lost if break with pickaxe.
2. It does not work as described: 
I put 10 gold ore pieces, aura level was above 50% and I get exactly 10 ingots.
Then I tried another 10 gold ore pieces with aura level almost 100% and again get exactly 10 ingots.
Screenshot of scheme with hoppers is in attachment.

![2022-09-20_10 03 31](https://user-images.githubusercontent.com/96169906/191179697-b4a2d138-5d8c-428a-b5e7-f6b82fd07e4a.jpg)

**Comment by uhloin** [comment]
Corporeal eye also is not dropped

**Comment by uhloin** [comment]
Golden stone bricks also are not dropped by pickaxe.

**Comment by klutzies** [comment]
The Cloudshifter also drops nothing when broken.
(The second bug in the original post should probably be split into a separate issue.)
