### ISSUE TITLE
Imperceptible builer stops working

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#282]
Tha farm on the screenshot worked good but since some version stops working. As you can see aura level is OK and seeds are gathering but it does not re-planted crops. But I still can hear sound like if they replanted but they not and this sound is repeating infinitely. If I plant seed myself on the all empty places with plowed soil in 5 blocks from builder then sound stops.

![nature_imperceptible_builder_bug](https://user-images.githubusercontent.com/96169906/199194486-57146f78-2743-4c91-91e1-0bff5cf0781a.png)

**Comment by uhloin** [comment]
Additional screenshot
![bug2](https://user-images.githubusercontent.com/96169906/199195664-bf149beb-388c-4491-8d2e-24428bafbfdc.png)

**Comment by uhloin** [comment]
Versions: 
minecraft 1.19.2
forge-1.19.2-43.1.47-installer.jar 
NaturesAura-37.4.jar

**Comment by Ellpeck** [comment]
Do you have any sort of chunk protection mod enabeld? If so, you'll have to add the Nature's Aura fake player (whose data is printed in the game's log file) to the chunk protection mod's allowed player list, or disable the chunk protection in this area.

**Comment by uhloin** [comment]
Thank you! It was Minecolonies mod.
