### ISSUE TITLE
[1.18.2] Natural Alter, Golden Bricks, and Golden Netherbricks do not drop block item when broken

### ISSUE THREAD

**Issue by DelviousCrafts** [Ellpeck/NaturesAura#284]
As the title suggests, when broken (which takes ages with all tools, including an empty hand) the block item does not drop for the Natural Alter, Golden Bricks, and Golden Netherbricks. 

Tested in a minimal environment with just Nature's Aura and Patchouli installed to verify.

Versions:
- Minecraft: 1.18.2
- Forge: 40.1.86
- Nature's Aura: 36.3
- Patchouli: 71.1

**Comment by Ellpeck** [comment]
(*See https://github.com/Ellpeck/PrettyPipes/commit/6d5a805160501a0ca5a491d69bd6e2ce7f420a16*)
