### ISSUE TITLE
Mekanism Radiation interaction

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/NaturesAura#289]
Possibly a simple suggestion. Allow Aura to clean up Mekanism Radiation.

The way I'm envisioning this would be that if radiation gets into unsafe levels (basically anything above the 'baseline'), then Aura will be rapidly consumed to reduce it. 

Aura cost could go one of two ways:

Safe Way: If Aura is above a certain positive threshold, it is drained to clean the radiation
Unsafe Way: No lower threshold exists and Aura is always drained, causing all the negative effects associated with low Aura if the spill was bad enough.

Naturally, a config option to choose between these or turn it off completely would probably be prudent :D

**Comment by Ellpeck** [comment]
Sorry, but I doubt this will ever happen!
