### ISSUE TITLE
Ticking Memory Connection

### ISSUE THREAD

**Issue by O13SC3N3** [Ellpeck/NaturesAura#29]
Posted at Patchouli, when adding Natural Auras throws the issue, when removed Issue doesn't exist.

https://github.com/Vazkii/Patchouli/issues/106

1.12.2 Minecraft Forge 2768

https://paste.dimdev.org/igukayujax.mccrash

Posted on Patchouli "Not sure whats going on back tracking to see if another mod is Involved but the error is stating Patchouli On World Creation and Modpack load everything is fine, everything loads smooth and the console reports errors with Advancements which seems to be the norm. However once save and quitting which is also fine, when you got to reopen the world It throws this error and will not reload. You can create a world just fine and play, until you save and exit and want to play again."

**Comment by Ellpeck** [comment]
Cannot reproduce with just Nature's Aura and Patchouli.
As Nature's Aura is probably the only mod in your modpack that actually adds compatibility for it, Patchouli wouldn't even do anything without Nature's Aura installed, meaning the issue wouldn't happen.
This is almost certainly a different mod causing the actual issue if Patchouli and a mod that uses it are present.

**Comment by Ellpeck** [comment]
Do you have a mod installed that removes any advancements, specifically ones from Nature's Aura?

**Comment by O13SC3N3** [comment]
Not sure, searching through all the configs, and wikis now.

**Comment by Ellpeck** [comment]
So you tried without any other mods other than Nature's Aura and Patchouli?

The log is very interesting, as the game can't load a bunch of normal vanilla advancements. It seems like ReSkillable is somehow involved, but I wouldn't say that this issue is necessarily caused by it.
Have you tried using a new Forge/Minecraft installation?

**Comment by O13SC3N3** [comment]
Disabling Reskillable + CompatReskill still throws all the advancement issues (When I searched online I guess this is common in 1.12.2?) However the world loaded. So im thinking something going on with Reskillable and the player data with Advancements they use to unlock skills?

Ive actually have Reskill and Compat disabled by default (Was intending on in the future to utilize it to restrict a lot of tinker's materials and items with it to tier a bit)

**Comment by Ellpeck** [comment]
Yea Reskilable creates a new AdvancementManager on the client for some reason I'm not quite sure, and that seems to be causing the issues.. maybe? I don't know, I haven't checked thoroughly, obviously. It seems like this is resolved now, though.
