### ISSUE TITLE
oak trees whose growth is blocked to grow large-only can't grow at all, generating no aura

### ISSUE THREAD

**Issue by rosemarymouse** [Ellpeck/NaturesAura#291]
background: placing a glass block one block above and to the side of an oak sapling will make it only capable of growing "large".

what I expected:
- when blocked and forced to grow large, an oak sapling will be prevented from growing at all and will always stay a sapling
- when it WOULD'VE grown, whether naturally or with bonemeal, aura will generate (since the growth would've been large)

what I got:
- the sapling cannot be grown at all, even with bonemeal (working as expected)
- no aura is ever generated (unexpected)

whether or not this is a bug of a feature is a matter of balance I think, but I thought I was clever for coming up with the idea only to be a bit disappointed when it didn't work out :P

**Comment by Ellpeck** [comment]
What Minecraft and Nature's Aura versions are you trying this on?

**Comment by rosemarymouse** [comment]
minecraft 1.19.2, nature's aura 37.5!

**Comment by rosemarymouse** [comment]
for what it's worth, I can see how this could be entirely intended behavior. blocked-off oak saplings generating free aura with no maintenence required could be considered undesirable/unbalanced/etc. as it stands right now, other than this edge case which is more a matter of taste, the generator appears to be working perfectly
