### ISSUE TITLE
Book of natural aura resets after crash in mod version 34.4, minecraft 1.16.5

### ISSUE THREAD

**Issue by BlueWhiteBrosH** [Ellpeck/NaturesAura#298]
My book of natural aura got reset after a crash and it doesn't unlock anymore.  Is there any way to force unlock things?

**Comment by Ellpeck** [comment]
You can unlock the entire book for your current player using the command `/advancement grant @p from naturesaura:root`. You can also go into the Patchouli config file and disable advancement progression altogether.

**Comment by Ellpeck** [comment]
Could you report this issue to the Patchouli repository and maybe cross-reference this issue as well? I'm not sure this is something for Nature's Aura to fix. Thanks!!
