### ISSUE TITLE
Thaumcraft Issue w/ Visualizing

### ISSUE THREAD

**Issue by sleepyKitsune** [Ellpeck/NaturesAura#3]
![2018-11-11_13 26 53](https://user-images.githubusercontent.com/37781809/48316868-13470f00-e5b7-11e8-8422-a25e72c27e12.png)
I had this issue when Loading up the mod and trying to visualize the tree altar.

Mods Installed:

Baubles
JEI
Nature's Aura
Patchouli
Thaumcraft
FORGE: 14.23.5.2772

**Comment by Ellpeck** [comment]
This is a Patchouli issue, please report it there.
