### ISSUE TITLE
[Bug] Crumbling and Transmutation Catalysts won't work properly

### ISSUE THREAD

**Issue by danzio** [Ellpeck/NaturesAura#30]
It is unable to place any items on Natural Altar except blocks like sand (for making soulsand via Transmutation) or glowstone (for making glowstone dust via Crumbling). Iron ingot for basic Infusing to Infused Iron can be placed without any problems.

**Comment by Ellpeck** [comment]
Oof, this is a fun issue.
You can still input them using a hopper though, so you can do that as a workaround for the time being.
