### ISSUE TITLE
Crimson Meal not working as intended?

### ISSUE THREAD

**Issue by Feppeltanten** [Ellpeck/NaturesAura#300]
Playing in game version 1.18.2, Mod version 36.3. In the book it says that Crimson Meal can make nether warts grow into bigger versions of itself when applied, however, this doesn't work. I have spammed 500 crimson meals on a plant in an open field to test it.

Any idea what could be causing this? I'm playing in the FTB Inferno pack, if that's important.

**Comment by Feppeltanten** [comment]
> Unfortunately the 1.18.2 version isn't supported anymore other than for gamebreaking issues. Can you try to reproduce this behavior in the 1.19.2 version? Thanks!

Ah, I see! Unfortunately I am only playing in 18.2 because of the modpack, so I can't test it out :/ But I appreciate the quick response!

**Comment by Ellpeck** [comment]
This seems to work correctly in 1.20.1.
