### ISSUE TITLE
Game crash - ConcurrentModificationException

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Ellpeck/NaturesAura#305]
Versions:
- Nature's Aura: 36.3
- Forge: 40.2.1

[crash-2023-04-03_10.14.01-client.txt](https://github.com/Ellpeck/NaturesAura/files/11140800/crash-2023-04-03_10.14.01-client.txt)

**Comment by DigitalArtist36** [comment]
I am having the same issue with crashing when attempting to rejoin world
[crash-2023-06-21_11.36.33-client.txt](https://github.com/Ellpeck/NaturesAura/files/11840823/crash-2023-06-21_11.36.33-client.txt)

**Comment by embeddedt** [comment]
I encountered the same crash on ATM8. The stack trace and time of crash are identical to what was posted above so I haven't attached a crash report.
