### ISSUE TITLE
[Bug] Book of Natural Aura (guidebook) has sections gated or locked off.

### ISSUE THREAD

**Issue by hairlessOrphan** [Ellpeck/NaturesAura#309]
Trying to learn the mod, opened up the guidebook, it looks like sections of the guidebook are "locked," which can't be right. Like, the documentation for the mod is gatekept? Seems like a bug.

Originally thought this might be an interaction with Eccentric Tome, but after crafting just the Book of Natural Aura book directly, still seeing most of the documentation "locked."

**Comment by Ellpeck** [comment]
Hi! This is the way advancement unlocking with Patchouli works. This system is meant to guide you through the mod by only unlocking sections for items that you're actually able to craft and use with the current stage of your progression. One of the introductory chapters in the book explains this behavior and how to use it.
