### ISSUE TITLE
Crafttweaker

### ISSUE THREAD

**Issue by Fortist** [Ellpeck/NaturesAura#31]
Before dumpster diving into the source/dumpzs, is there any examples of the crafttweaker recipes?

**Comment by Ellpeck** [comment]
Not yet, but there shall be some soon.

**Comment by Fortist** [comment]
It's alright I had already dived and made some recipes when posting.
A few hiccups with the string, No OreDict entries allowed (which makes some recipes annoyingly specific, but I digress) and wondering what aura amount to use, unsure if it's a per tick amount or a flat amount.
The first hurdle was wtf "NaturesAura.MODID" was, but being an idiot, it was simply just the modID. "naturesaura"

Next was a test and I didnt realize I needed a string, so got that issue.
After was the trying to use an array of items in a recipe, which failed.
After that was using Oredict, which failed.
So, after figuring out the rules, everything fell into place.

```
import mods.naturesaura.TreeRitual;
import mods.naturesaura.Altar;
import mods.naturesaura.AnimalSpawner;
import mods.naturesaura.Offering;

[TreeRitual/Altar/AnimalSpawner/Offering].removeRecipe(<Item Output>);

TreeRitual.addRecipe("STRING", <Sapling Input>, <Item Output>, Tick Time, [<Array>, <of Items>]);
Altar.addRecipe("STRING", <Item Input>, <Item Output>, <Catalyst>, Aura, Ticktime);  (Im unsure if the catalyst can be set to "null," havent tried yet.)
AnimalSpawner.addRecipe("STRING", "Mob ID", Aura, TickTime, [<Array>, <of Items>]);
Offering.addRecipe("STRING", <Item input>, <Offering/Item>, <Item output>);
```
This was mostly spurred on because the very first Tree Ritual recipe, Ancient Trees, seemed to not work due to having Sugar Canes go missing in both the book and JEI, no idea what mod interaction (Or resource pack interaction, if possible) broke the recipe.

**Comment by Ellpeck** [comment]
The rules are just CraftTweaker's default rules 🤔

**Comment by Shadows-of-Fire** [comment]
Oredict doesnt work because your methods require IItemStack for item input, they should require IIngredient instead.
