### ISSUE TITLE
[1.19.2] Crash with armor upon freshly new made world? 

### ISSUE THREAD

**Issue by Gbergz** [Ellpeck/NaturesAura#315]
Title^

MC: 1.20.1
Forge: 43.2.14
Nature's Aura: 38.0

Crash-Report: https://gist.githubusercontent.com/Gbergz/0de440fbb390c8797156ee67e7499550/raw/3da9f8271cf4903a9f1667e6240051b183b8ec5c/gistfile1.txt

**Comment by Ellpeck** [comment]
Hi! This has already been fixed in 38.1.

**Comment by Gbergz** [comment]
Ah, should've checked. Beforehand. Apologies.
