### ISSUE TITLE
Shooting mark doesn't work

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#317]
Minecraft 1.19.2
NaturesAura-38.2.jar 

Set Shooting Mark to ground, shoot with bow to the side with red target. It doesn't rotate. It worked fine some time ago.

**Comment by Ellpeck** [comment]
What is the aura level around the shooting mark? Do you have a creational catalyst under it?

**Comment by uhloin** [comment]
1. 60%
2. No

**Comment by Ellpeck** [comment]
Please try attaching a creational catalyst. Most aura generators have a higher detection range for aura than the environmental eye does, so chances are that the shooting mark doesn't work because it's detecting that the surrounding aura is too high.

**Comment by uhloin** [comment]
Thank you, yes, it works with catalyst. It's still not clear, why herb. absorber go to 100% without catalyst, but shooting mark stops on some lower level... 66%? The in-game manual say nothing about it.
