### ISSUE TITLE
Aura Field Creator does not work in "Shears" mode

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#324]
In the Book there is a recommendation to place frame with shears on the side of one of Aura Field Creator-s. But it's impossible, because for this the right mouse click should be used, and the same right mouse click is used to connect field creators. 

Also this thing is very slow and little of use. I would prefer it "cut" full-grown golden leaves when they are ready for automatic farm.

Version is NaturesAura-39.0

**Comment by Ellpeck** [comment]
You should be able to sneak-right-click to place the item frame on the aura field creator.

**Comment by uhloin** [comment]
No, it doesn't work too, because sneak+right-click is reserved for second aura creator to connect them.
I'm trying again and now It stopped work at all.
Empty hand, right click -- "Your notes seem out of date"
Trying other creator -- "The distance seems to great" (distance is 3 empty blocks between)
My key binds: left ctrl = sneak, space = sprint, shift = jump
Ctrl+right click, shift+right click doesn't work

**Comment by uhloin** [comment]
Also, I'm not sure about one more bug or just unbalanced thing therefore not write as bug.
In the manual the Rose of Oblivion mentioned as powerful end game thing, but it's not powerful, but just expensive and disappointment. End eye is not cheap thing, killing of a dragon is also cost time and some resources, but Rose adds only +10-20% of aura and converted to Dead Bush. It's much more effective to spend those arrows to shooting mark, not to a dragon.

**Comment by Ellpeck** [comment]
Hi! Between 20 and 100 Roses of Oblivion will be generated every time the Ender Dragon dies. These are a very quick and powerful way to replenish a very large amount of Aura in an area.

**Comment by uhloin** [comment]
Just compare -

1. Spend about 100 arrows and at least 10 minutes to a dragon, 10 minutes to find and gather 20-100 roses, kill 20-100 Endermans (+?? munites), kill 20-100 Blazes (+?? minutes), spend about 5-10 of roses to generate 100% aura. The last step may be automated, but not very simple and also cost some time.

and

2. Spend 100 arrows to make the same ... in 30 sec with simple machine with 4 dispensers.

**Comment by Ellpeck** [comment]
You're not expected to farm Roses of Oblivion, or kill the dragon specifically for them. They're an added reward for killing the Ender Dragon that you can cash in for Aura.

**Comment by uhloin** [comment]
Ok, it's unprofitable because need to spend ender eyes, but at least it's useful as component for env. ocular
