### ISSUE TITLE
Imperceptible Builder in MC 1.20.1

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#325]
it's useful for automatization of the forest to place gold powder and to place sapling, but it doesn't work to place items to wooden stands with frame with wooden stand on the side on imp. builder and chest with items above the builder. Moving builder up/down doesn't help too.

**Comment by Ellpeck** [comment]
I'm sorry, I don't think I understand what you mean? The imperceptible builder only places blocks in the world, it can't place items into inventories. To place items into wooden stands automatically, you can use a hopper or other item transport solutions from other mods.

**Comment by uhloin** [comment]
May be wooden stands are inventories on the programming level, but try imagine the point of view of player. The item on the wooden stand and... gold powder on the wooden planks -- they look very similar and expect the same interaction. I'm not sure there is a solution with hoppers with reasonable complexity and usability except if I just fill every hopper with stack of the same item. It's really good for Natural Altar but the the ritual of the forest doesn't assume of production many items of the same type. Usually I use the ritual to make one thing, different thing on the next step etc. I do not know, may be It would be great if support JEI to place all items with minimum clicks? Or something like special crafting table to place items to it and auto-distribute to wooden stands? Or just allow wooden stand to work like crafting table and auto-distribute items to other near stands?
