### ISSUE TITLE
Adept Hopper in MC 1.20.1

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#326]
1. The manual writes that sneak+right click must switch mode of Adept Hopper from normal to inverted, but it does not say it must be done with empty hand and even more -- shield must be removed because else it is just resolved to sneak and shield blocking. Probably switching should have higher priority than blocking by otherhand or any operation with main hand.
2. How to see the content of the adept hopper like content of normal hopper? Right click doesn't work.

**Comment by Ellpeck** [comment]
Hi! The amount of stored items of the Adept Hopper can be seen when hovering over it with an Environmental Eye equipped, as stated in the Book of Natural Aura.

![image](https://github.com/Ellpeck/NaturesAura/assets/5741138/07e14d32-c152-4031-8eee-d2200398526b)
