### ISSUE TITLE
Corrupted save (possible cause: Aura Imbalance Ward connected to 2 furnaces)

### ISSUE THREAD

**Issue by uhloin** [Ellpeck/NaturesAura#328]
I got a corrupted save which is loaded only without Nature Aura

Cannot send save because it's too big bug :) 7Gb But I have a version about cause

Symptom is: Minecraft itself is loaded but on attempt to load save file I get "Java ... not responding" and need to stop it.

[crash-2023-09-23_03.13.02-server.txt](https://github.com/Ellpeck/NaturesAura/files/12705050/crash-2023-09-23_03.13.02-server.txt)
Attached a crash-report 

Between good and bad saves I tried to get all advancements for Nature Aura, including made and enchant Soulstrider's armor and tools. But as possible cause I suspect Aura Imbalance Ward. Because it's craft is expensive I tried to connect it to 2 furnaces. Looks like this worked but may be this was not expected and make problem during loading.

Cannot screenshot because cannot load but I remember such confuguration:
_B
FW
Here: 
B is a Blast Furnace with Armorer's Aid above it and Extraneous Firestarter on the side. Hopper 1 and double chest are above, and hopper 2 is below.
F is regular Furnace with additional separate Extraneous Firestarter on the side. Also hopper 3 and double chest are above, and hopper 4 is below.
W is Aura Imbalance Ward connected to both Blast Furnace and regular Furnace.
Hopper 2 and hopper 4 connected to hopper 5 below W and hopper 5 is connected to double chest.

Additional possible important things.
Before create this configuration I connected Ward to only blast furnace, but break it and rebuild to connect to both.
Also looks like ward triggered once, stopped work and to resume I removed items and put again.

**Comment by Ellpeck** [comment]
Hi! For the time being, you can enable the `removeErroringTileEntities` (or something like that) configuration in Forge's configuration file (either `forge-common` or `forge-server`), which should automatically remove any block entities that cause errors. Take care to disable it again after loading the save, though!

**Comment by Ellpeck** [comment]
Actually, it looks like this might be an issue with Lithium. Can you try removing Lithium, but not Nature's Aura, and report back? Thanks!!

**Comment by uhloin** [comment]
Both methods did not help, error is the same:

[crash-2023-09-23_13.43.46-server.txt](https://github.com/Ellpeck/NaturesAura/files/12706109/crash-2023-09-23_13.43.46-server.txt)

I removed port of lithium (radium-mc1.20.1-0.11.2-SNAPSHOT.jar)
and set both
	removeErroringBlockEntities = true
	removeErroringEntities = true
in corrupted save

I used MCA Selector to delete possible buggy machine but this also didn't help

I will try to figure invalid chunk and decrease size of world to make possible attach it, but this probably will take time

**Comment by Ellpeck** [comment]
Does this issue also occur with *just* Nature's Aura and Patchouli installed?

**Comment by uhloin** [comment]
Yes

**Comment by uhloin** [comment]
Here is minimized corrupted save
[badfile.zip](https://github.com/Ellpeck/NaturesAura/files/12706251/badfile.zip)

**Comment by uhloin** [comment]
When loaded this save player will stuck underground and cannot mode, game is not responding
When loaded this save without mods player will born underground but can move and dig out

Mods:
NaturesAura-39.1.jar 
Patchouli-1.20.1-81-FORGE.jar 

Forge:
forge-1.20.1-47.1.76-installer.jar 

MC
1.20.1

**Comment by uhloin** [comment]
A single Aura item in this chunk is Aura Evaporizer, but it works well in previous save

**Comment by Ellpeck** [comment]
I assume this issue is still occuring and you closed it by accident?

**Comment by uhloin** [comment]
Yes, sorry
