### ISSUE TITLE
Additional Flowers

### ISSUE THREAD

**Issue by Fortist** [Ellpeck/NaturesAura#33]
I havent made the leap to 1.13+ conventions of "properties" yet so Im unsure how exactly the config reads blocks with metadata. It probably has to do with "variants" but im stuck in the old ways.

So which one of these work?
```
minecraft:tallgrass:1
minecraft:tallgrass
minecraft:tallgrass[1]
minecraft:tallgrass[prop1=1]
```
Though, I'd say with one of these it seems like air blocks seem to be sucked by the Herbavoral whatever machine.

**Comment by Mowmaster** [comment]
Variants in 1.13 need to be limited to things like BlockDirectional (x,y,z placement things) not things like red or yellow wool

**Comment by Ellpeck** [comment]
For the block you need, have your crosshair over it and then look to the right side of the F3 debug screen. You'll see the name of the block will all the properties and their values lined up on the right. That's what you need to put into the file.

**Comment by Fortist** [comment]
SO....
```
minecraft:tallgrass[type:tall_grass]
inspirations:flower[type:cyan, metadata: 3]
```
???

**Comment by Ellpeck** [comment]
No, with the actual syntax that the config explains to you.
`minecraft:tallgrass[type=tall_grass]`
`inspirations:flower[type=cyan,metadata=3]`

**Comment by Ellpeck** [comment]
(For future questions, you should probably join the [Discord Server](https://ellpeck.de/discord) as this issue tracker is more meant for.. issues than for general questions :D
