### ISSUE TITLE
Staff of Riches doesn't mark Lootr instanced loot (chests/barrels/etc)

### ISSUE THREAD

**Issue by TemporalWolf** [Ellpeck/NaturesAura#332]
Not sure if this is an issue on your side or theirs, but this would drastically improve the functionality of the staff.

Nature's Aura 39.2
Lootr 0.7.29.68
MC 1.20.1
(FTB DW20 1.20 1.2.0)

**Comment by micmou** [comment]
I can confirm that this is a issue and it would be nice to have it fixed.

Natures Aura 39.2
Lootr 0.7.29.68
MC 1.20.1 Neoforge 47.1.79
