### ISSUE TITLE
Game Crash, when i entry in nether biome

### ISSUE THREAD

**Issue by MickaNoob** [Ellpeck/NaturesAura#335]
Hi, i got game crash, mb in error log, naturesAura is mentioned, do you have idea? 

I got latest version.

https://mclo.gs/9hPHLxF

**Comment by Ellpeck** [comment]
Patchouli is a required mod for Nature's Aura to work, and weirdly, it looks like that it was not installed, but the game still launched correctly, which... I don't think Forge is supposed to be able to do.

**Comment by MickaNoob** [comment]
I have install the mod after the post, but crashes are always present.

**Comment by Ellpeck** [comment]
Can you please share the crash report from the crash that you get after installing Patchouli?

**Comment by MickaNoob** [comment]
Okay i have found the problem. Rubidium cause crashes, i have just remove it and it's ok.
