### ISSUE TITLE
Soulstrider Armor Effects apply to all Server Players

### ISSUE THREAD

**Issue by coreXtream** [Ellpeck/NaturesAura#336]
On our Server, some players use the Soulstrider armor, and upon hit the slowness or stun effect applies to all players on the server. Is this an intended function? Cause the description only says in the near area.
As for mods that could interfere somehow with the "Enemy Groups" whatever, we only use scoreboard teams and the ftb teams Mod.

**Comment by Ellpeck** [comment]
Thanks for the report!

But also: Was I just asleep when I made that effect? How many more bugs could it possibly have? It's, like, three lines of code. Bleh.
