### ISSUE TITLE
Nature altar not working in other dimension

### ISSUE THREAD

**Issue by Kiriao** [Ellpeck/NaturesAura#337]
I was playing a mod pack call atm9 and was trying to make a altar at the other dimension call the beyond and the altar not working i have a way of generating aura

**Comment by Ellpeck** [comment]
The Natural Altar only works in dimensions that have sunlight aura, which is the aura from the overworld. If it's a specific dimension that the modpack doesn't have an aura type set for, you can do so in the Nature's Aura config.

**Comment by Kiriao** [comment]
> The Natural Altar only works in dimensions that have sunlight aura, which is the aura from the overworld. If it's a specific dimension that the modpack doesn't have an aura type set for, you can do so in the Nature's Aura config.

But I have a aura bar at my screen. Can I have an example how to add dimension in the config?

**Comment by Ellpeck** [comment]
The description of the config option explains what to do :)

> Additional dimensions that map to Aura types that should be present in them. This is useful if you have a modpack with custom dimensions that should have Aura act similarly to an existing dimension in them. Each entry needs to be formatted as dimension_name->aura_type, where aura_type can be any of naturesaura:overworld, naturesaura:nether and naturesaura:end, and entries follow standard TOML array formatting (https://toml.io/en/v1.0.0#array).

**Comment by Kiriao** [comment]
so i just add ["allthemodium:the_beyond", "naturesaura:overworld"]?

**Comment by Ellpeck** [comment]
If that is the name of the dimension, yes! You probably have to leave out the spaces around the arrow, though.
