### ISSUE TITLE
Ritual of the forest (ancient tree sapling) isn't working

### ISSUE THREAD

**Issue by Turmfalke2** [Ellpeck/NaturesAura#34]
hi,
I have no idea what I am doing wrong.
I have build the ritual place using the books guide (it registered as finished), placed all items (sapling, poppy, dandelion, gold leaf and seeds), but when the sapling in the middle grows I get normal regular tree.

![2019-02-23_13 41 20](https://user-images.githubusercontent.com/5174562/53286591-2e5a1b00-3771-11e9-9b6e-a995f33b0186.png)

Tried it multiple times, it just doesn't work and there is no indication on what is missing.

**Comment by Quarris** [comment]
Are you sure you're not missing an item? Looks like there is no sugar cane on any of the stands

**Comment by Ellpeck** [comment]
You're missing Sugar Cane.

**Comment by Turmfalke2** [comment]
Because there is no sugar cane in the recipe...
![2019-02-23_23 13 30](https://user-images.githubusercontent.com/5174562/53292296-a996ed80-37c0-11e9-8379-c9fcf92b124c.png)

 I guess it is supposed to go in the top left slot?

**Comment by Ellpeck** [comment]
![image](https://user-images.githubusercontent.com/5741138/53292312-e06d0380-37c0-11e9-996a-0de26b060fad.png)
The recipe is very clearly there for me, so.. cannot reproduce, I guess 🤔

**Comment by Ellpeck** [comment]
Please try to reproduce this issue with just Nature's Aura installed and see what other mods that you have might be causing it.. somehow.

**Comment by Turmfalke2** [comment]
Guess it could be a mod conflict, I am playing [Magical Progression](https://minecraft.curseforge.com/projects/magical-progression).
However I can't see any recipe changes for the ancient sapling.


- recipes.remove(<naturesaura:calling_spirit>);
- recipes.remove(<naturesaura:shockwave_creator>);
- recipes.remove(<aether_legacy:nature_staff>);
- recipes.addShaped(<naturesaura:calling_spirit>, [[null, <naturesaura:aura_bottle>, null],[<botania:manaresource>, <botania:manaresource:2>, <botania:manaresource>], [null, <naturesaura:aura_bottle>, null]]);
- recipes.addShaped(<naturesaura:shockwave_creator>, [[null, <embers:dust_ember>, null],[<midnight:tenebrum_ingot>, <nex:amethyst_crystal>, <midnight:tenebrum_ingot>], [null, <naturesaura:aura_bottle>.withTag({stored_type: "naturesaura:nether"}).onlyWithTag({stored_type: "naturesaura:nether"}), null]]);
- recipes.addShapeless(<botania:corporeaspark>, [<botania:spark>,<naturesaura:aura_bottle>,<astralsorcery:itemcraftingcomponent:2>]);
- recipes.addShaped(<aether_legacy:nature_staff>, [[null, <aether_legacy:zanite_gemstone>, null],[null, <naturesaura:ancient_stick>, null], [null, null, null]]);
- recipes.addShaped(<botania:manatablet>, [[<botania:livingrock>, <botania:livingrock>, <botania:livingrock>],[<botania:livingrock>, <naturesaura:aura_cache>, <botania:livingrock>], [<botania:livingrock>, <botania:livingrock>, <botania:livingrock>]]);
- recipes.addShaped(<astralsorcery:blockaltar>, [[<chisel:marble>, <naturesaura:sky_ingot>, <chisel:marble>],[<chisel:marble>, <midnight:shadowroot_crafting_table>, <chisel:marble>], [<chisel:marble>, null, <chisel:marble>]]);
- recipes.addShaped(<totemic:totem_whittling_knife>, [[null, null, <naturesaura:infused_iron>],[null, <naturesaura:ancient_stick>, <minecraft:flint>], [<naturesaura:ancient_stick>, null, null]]);
- recipes.addShaped(<botania:spreader>, [[<botania:livingwood>, <botania:livingwood>, <botania:livingwood>],[<naturesaura:gold_powder>, <botania:petal>, <minecraft:glass_pane>], [<botania:livingwood>, <botania:livingwood>, <botania:livingwood>]]);
- mods.botania.ManaInfusion.addInfusion(<botania:manaresource>, <naturesaura:infused_iron>,1000);
- mods.botania.PureDaisy.addRecipe(<naturesaura:infused_stone>,<botania:livingrock>);
- mods.botania.PureDaisy.addRecipe(<naturesaura:ancient_bark>,<botania:livingwood>);
- mods.botania.PureDaisy.addRecipe(<naturesaura:ancient_log>,<botania:livingwood>);

**Comment by Turmfalke2** [comment]
@Ellpeck found it.

I can reproduce it with a clean 1.12.2 minecraft + 2815 forge and the following mods:
 - Patchouli 1.0-16
- Nature's Aura r12
- Placebo 1.12.2-1.5.1
- Apotheosis 1.12.2-1.5.0

**Comment by Ellpeck** [comment]
But without Placebo and Apotheosis, you cannot?

**Comment by Turmfalke2** [comment]
Yes, it is something about apotheosis and it's depency placebo. Also the recipe still works, it just isn't showing the sugar cane.

**Comment by Ellpeck** [comment]
Can you please confirm that, with r14 of Nature's Aura, this issue is fixed?

**Comment by Shadows-of-Fire** [comment]
The changelog of the modpack mentioned it was fixed

**Comment by Turmfalke2** [comment]
can confirm, it is fixed.
