### ISSUE TITLE
Nature Altar not working in simple void world dimension (Simple Void World Mod)

### ISSUE THREAD

**Issue by teatcda2006** [Ellpeck/NaturesAura#341]
I don’t know what to write in the config where "dimension_name" and in what format

**Comment by Ellpeck** [comment]
Hi :) As explained in the comment for the configuration:
> Each entry needs to be formatted as dimension_name->aura_type, where aura_type can be any of naturesaura:overworld, naturesaura:nether and naturesaura:end, and entries follow standard TOML array formatting (https://toml.io/en/v1.0.0#array)

So for example, if you had a dimension whose registry name is "dimension_mod:cool_dimension", and you want it to have the same aura as the overworld, you would put this as the value:
```toml
["dimension_mod:cool_dimension->naturesaura:overworld"]
```

Good luck!
