### ISSUE TITLE
Field creator failed to work in ftb claimed chunk---1.19.2 Version 38.1

### ISSUE THREAD

**Issue by Forever819** [Ellpeck/NaturesAura#349]
As the titled saied,field creator failed to work in ftb claimed chunk.maybe is the permission cause the problem?

**Comment by Forever819** [comment]
![recording](https://github.com/Ellpeck/NaturesAura/assets/69418544/43621656-5b71-47c0-8c38-7fe343832e10)

**Comment by Ellpeck** [comment]
Hi! You need to add the fake player that Nature's Aura uses to a list of exceptions. I vaguely remember FTB Chunks having a special setting in its chunk claim settings for "allow fake players", which should do the trick :)
