### ISSUE TITLE
Unlimited Aura?

### ISSUE THREAD

**Issue by Draken42** [Ellpeck/NaturesAura#35]
Icelingbolt's pack Magical Progressions, from Curse/Twitch launcher, pack version 0.75, mod version r11
(according to ingame mod view)

I recently crafted a botanists pickaxe, and upon reading that it could add moss to blocks, I made a Swamp Homi. Using my pickaxe and a block of cobblestone, I then fueled the Swamp Homi for increasing Aura, as measured by my Environmental Eye. I just need to repair the pickaxe with an Aura Cache, which consumes less Aura than the whole scheme produces. Note: I also have an ancient tree, which can pick up the slack if I am infusing iron, refueling the cache, or taking time to repair my pickaxe.
Anyway, this is a little OP, because it seems very easy to automate, although I have not yet done so.
Is this meant to happen?
Screenshots

![broken homi](https://user-images.githubusercontent.com/47921973/53288216-060ff380-3754-11e9-917a-c39fd374a5f4.jpg)

The whole setup

![broken homi moss](https://user-images.githubusercontent.com/47921973/53288169-60f51b00-3753-11e9-8fd9-b358c53adc64.jpg)

Me adding moss, moss converting to aura

![broken homi altar](https://user-images.githubusercontent.com/47921973/53288170-65b9cf00-3753-11e9-8418-26875d01f276.jpg)

The altar recharging my cache after pickaxe repair, and barely losing any power

**Comment by Ellpeck** [comment]
I don't think this is easy to automate, unless you can prove otherwise.

**Comment by Draken42** [comment]
Sorry, good point. I thought about it some, and realised that you would probably need automation in other mods first in order for an automated system to function well without the player resupplying it.

**Comment by Ellpeck** [comment]
I don't think any mod even exists that would allow you to have a block that you give both the Aura Cache and the pickaxe to and it would recharge the pickaxe from the Aura Cache. You'd need for it to emulate a proper player inventory, as well as for it to be genuinely sneaking.  
You'd have to supply the thing with iron to do an automation using the pickaxe, and I'm fine with that.

**Comment by Draken42** [comment]
You could just autocraft pickaxes. A little wasteful but it would work. You could also repair the pickaxe with an auto anvil. But again, that would need lots of work in other mods.

**Comment by Draken42** [comment]
Thanks for setting me straight.

**Comment by Ellpeck** [comment]
I'd still love to see you (or anyone, really) attempt to automate this using the pickaxe method. It'd be a nice and impressive thing to see on Reddit or Youtube :D
