### ISSUE TITLE
NItpicks about dependencies!

### ISSUE THREAD

**Issue by ZestyBlaze** [Ellpeck/NaturesAura#354]
Hi! This isn't so much an issue but more a nitpick from a fellow mod developer and someone who plays mods!
When installing Nature's Aura for 1.20.4, it requires you to have Curios and Patchouli installed otherwise it causes a CNF error on start-up, however these files aren't marked as required in the `mods.toml`, nor do these dependencies automatically install on Curseforge app.
I've just got one of two suggestions:
1. Either reworking the `build.gradle` to not require these mods and marking them as optional mods in the `mods.toml` so they don't crash when not present in the mods folder and add integration when they *are* installed
Or
2. Adding both Curios and Patchouli as required dependencies on Curseforge so both of them are always automatically installed when you install Nature's Aura from the Curseforge app, and also flagging both of these mods as required dependencies in the `mods.toml` so if someone downloads it from the website and forgets these, the game will crash with a cleaner explanation as to how to fix it (Aka, telling the player to install Curios and Patchouli)

Hope this helps! <3

**Comment by Ellpeck** [comment]
Uh, well, Patchouli has always been a required dependency and is listed as such in the dependencies section of CurseForge and Modrinth.

Curios is not meant to be a required dependency at all, so that must've made its way in during a version port at some point, I guess.

**Comment by Ellpeck** [comment]
(But thanks for letting me know, of course! ❤️)

**Comment by ZestyBlaze** [comment]
![image](https://github.com/Ellpeck/NaturesAura/assets/68081568/deecf8df-2878-44b5-bb45-a8fdc9343f59)
Huh that's odd it's no longer listing Patchouli as a required dependency on Curseforge in the later 1.20.4 versions, weird why it's done that

**Comment by Ellpeck** [comment]
Ugh, that's annoying. Maybe the new interface doesn't automatically carry over the dependencies from old versions like the old interface used to, and I didn't notice.
