### ISSUE TITLE
Book Advancements Are Not Progressing

### ISSUE THREAD

**Issue by LacyDoes** [Ellpeck/NaturesAura#358]
I'm hosting a LAN server and my Partner and I can't progress the book.
Sometimes it works after a rejoin or restart but we've now reached a point where it doesn't progress anymore.
Nothing I can see shows in the logs, no errors that are obvious at least. 
I can supply logs or a mod list if needed!

# Minecraft Version 1.19.2 with 256 Mods Running FmL 43.3.0

**Comment by Ellpeck** [comment]
Hi! At first glance, this seems more like a Patchouli issue. Additionally, Minecraft 1.19.2 isn't supported anymore, unfortunately, so if it's not a Patchouli issue, there likely won't be a fix for this. Sorry!
