### ISSUE TITLE
Brilliant Fiber recipe broken on NeoForge 1.21.1

### ISSUE THREAD

**Issue by dainekoichi** [Ellpeck/NaturesAura#361]
![image](https://github.com/user-attachments/assets/96361e9a-c452-4448-b72c-9d0d5f894b3c)
![image](https://github.com/user-attachments/assets/6e49b4eb-8d46-48e3-a512-d5f428aaa097)

**Comment by Ellpeck** [comment]
I legit had on my to do list to go through the recipes and fix all the broken tags and evidently i just didn't do it lmao
