### ISSUE TITLE
Nature's Aura causing EMI/JEI exception

### ISSUE THREAD

**Issue by Gui1803** [Ellpeck/NaturesAura#363]
So, instead of rewriting the whole issue, I pasted a link to the report I made to the EMI. I don't understand much about this, so...

https://github.com/emilyploszaj/emi/issues/736#issue-2567462907

**Comment by Ellpeck** [comment]
Hi! Nature's Aura isn't officially compatible with EMI (yet). Can you confirm that this issue also happens using JEI? If not, this is a wontfix for now.
