### ISSUE TITLE
[NeoForge] - 1.21.1 - Nature's Aura PotionBreathless crashes the server

### ISSUE THREAD

**Issue by superhealing** [Ellpeck/NaturesAura#367]
Hello, i'm running server on ATM10 - 1.7
It appears it getting somewhat frequently crashes about
java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: Direct{de.ellpeck.naturesaura.potion.PotionBreathless@60751c43}

Crash log : https://hasteb.in/nNEfNpBE3c1M7Wr

P.S can you delete the other issue, please? Thank you.

**Comment by Ellpeck** [comment]
Hi! Why did you open this issue twice?

**Comment by superhealing** [comment]
Wrong account...

**Comment by PatrioticCross** [comment]
Having this issue as well

**Comment by DiglettsFeet** [comment]
Having this issue as well. 

[crash-2024-11-04_14.40.48-server.txt](https://github.com/user-attachments/files/17623263/crash-2024-11-04_14.40.48-server.txt)
