### ISSUE TITLE
Rain rendering breaks when Aura is high

### ISSUE THREAD

**Issue by MuteTiefling** [Ellpeck/NaturesAura#368]
My test instance consists of three mods
![image](https://github.com/user-attachments/assets/128af616-3d31-4500-835c-499254056737)
![image](https://github.com/user-attachments/assets/b73217f3-e204-4fa3-aef8-e6818d967934)

When Aura is low, rain looks normal. As it gets higher it glows bright white as shown in the video. Removing Nature's Aura resolves this issue.
https://streamable.com/fr6y1b

**Comment by Ellpeck** [comment]
Hmm, I can't reproduce this on any of the graphics settings, not even Fabulous :(

**Comment by MuteTiefling** [comment]
Yeah, not sure what the cause was but I've just reproduced my tests with the latest versions of everything and it seems to have been fixed somewhere along the way :D Gremlins.
