### ISSUE TITLE
No ritual is working

### ISSUE THREAD

**Issue by zEpiixz** [Ellpeck/NaturesAura#37]
![2019-03-02_23 57 24](https://user-images.githubusercontent.com/40037440/53688639-44ef0c00-3d47-11e9-9f99-9e19a94eef82.png)

I dont know why but the rituals are just not working for me.
This should be the simplest ritual and i cant seem to get it to work.

**Comment by Quarris** [comment]
Did you read the book? It has all the details of how it works, you are definitely missing things

**Comment by Ellpeck** [comment]
You're missing gold powder.

**Comment by zEpiixz** [comment]
god i feel so stupid right now. I was sitting there for 30 minutes figuring out whats missing. Because he consumed the gold when i was doing other stuff and the item i made despawned. Thanks anyways for helping my stupid mistake.
