### ISSUE TITLE
Add zh_CN.lang translations

### ISSUE THREAD

**Issue by ChirenCQR** [Ellpeck/NaturesAura#38]
itemGroup.naturesaura=自然灵气

tile.naturesaura.ancient_log.name=思古原木
tile.naturesaura.ancient_bark.name=思古木树皮
tile.naturesaura.ancient_leaves.name=思古树叶
tile.naturesaura.ancient_sapling.name=思古树苗
tile.naturesaura.nature_altar.name=自然祭坛
tile.naturesaura.decayed_leaves.name=腐叶
tile.naturesaura.golden_leaves.name=灿金树叶
tile.naturesaura.gold_powder.name=灿金粉
tile.naturesaura.wood_stand.name=木桩
tile.naturesaura.ancient_planks.name=思古木板
tile.naturesaura.infused_stone.name=注灵石
tile.naturesaura.furnace_heater.name=外置点火器
tile.naturesaura.potion_generator.name=药水吸收者
tile.naturesaura.aura_detector.name=灵气探测器
tile.naturesaura.conversion_catalyst.name=转型催化器
tile.naturesaura.crushing_catalyst.name=崩坏催化器
tile.naturesaura.infused_stairs.name=注灵石楼梯
tile.naturesaura.infused_slab.name=注灵石台阶
tile.naturesaura.infused_slab_double.name=注灵石双层台阶
tile.naturesaura.ancient_stairs.name=思古木楼梯
tile.naturesaura.ancient_slab.name=思古木半砖
tile.naturesaura.ancient_slab_double.name=思古木全砖
tile.naturesaura.infused_brick.name=注灵砖
tile.naturesaura.infused_brick_stairs.name=注灵砖楼梯
tile.naturesaura.infused_brick_slab.name=注灵砖台阶
tile.naturesaura.infused_brick_slab_double.name=注灵砖双层台阶
tile.naturesaura.flower_generator.name=植物吸收者
tile.naturesaura.placer.name=建筑者
tile.naturesaura.hopper_upgrade.name=漏斗升级器
tile.naturesaura.field_creator.name=灵气领域创造者
tile.naturesaura.oak_generator.name=树木吸收者
tile.naturesaura.infused_iron_block.name=注灵铁块
tile.naturesaura.offering_table.name=祭灵台
tile.naturesaura.pickup_stopper.name=拾物阻止者
tile.naturesaura.spawn_lamp.name=庇护灯
tile.naturesaura.animal_generator.name=动物吸收者
tile.naturesaura.end_flower.name=忘忧玫瑰
tile.naturesaura.grated_chute.name=Adept Hopper
tile.naturesaura.animal_spawner.name=动物生成器
tile.naturesaura.auto_crafter.name=自动构建者
tile.naturesaura.gold_brick.name=灿金石砖
tile.naturesaura.rf_converter.name=RF灵气锻炉
tile.naturesaura.moss_generator.name=苔藓吸收者
tile.naturesaura.time_changer.name=时间改变者
tile.naturesaura.generator_limit_remover.name=创造催化器
tile.naturesaura.ender_crate.name=末影板条箱
tile.naturesaura.powder_placer.name=粉末操纵者
tile.naturesaura.firework_generator.name=烟花吸收者

item.naturesaura.eye.name=环境之眼
item.naturesaura.eye_improved.name=环境观测镜
item.naturesaura.gold_fiber.name=闪耀纤维
item.naturesaura.gold_leaf.name=灿金叶子
item.naturesaura.infused_iron.name=注灵铁锭
item.naturesaura.infused_iron_pickaxe.name=植物学家之镐
item.naturesaura.infused_iron_axe.name=植物学家之斧
item.naturesaura.infused_iron_shovel.name=植物学家之锹
item.naturesaura.infused_iron_sword.name=植物学家之剑
item.naturesaura.infused_iron_hoe.name=植物学家之锄
item.naturesaura.ancient_stick.name=思古木棍
item.naturesaura.aura_cache.name=灵气储存器
item.naturesaura.color_changer.name=幻色桶
item.naturesaura.book.name=自然灵气宝典
item.naturesaura.shockwave_creator.name=激昂护身符
item.naturesaura.multiblock_maker.name=多方块结构木棍
item.naturesaura.aura_bottle.naturesaura:overworld.name=瓶装阳灵
item.naturesaura.aura_bottle.naturesaura:nether.name=瓶装魂灵
item.naturesaura.aura_bottle.naturesaura:end.name=瓶装冥灵
item.naturesaura.aura_bottle.naturesaura:other.name=瓶装常灵
item.naturesaura.farming_stencil.name=种植模板
item.naturesaura.bottle_two_the_rebottling.name=空瓶和塞子
item.naturesaura.sky_ingot.name=苍穹之锭
item.naturesaura.calling_spirit.name=号召之灵
item.naturesaura.birth_spirit.name=生成之灵
item.naturesaura.infused_iron_helmet.name=植物学家的头盔
item.naturesaura.infused_iron_chest.name=植物学家的盔甲
item.naturesaura.infused_iron_pants.name=植物学家的护腿
item.naturesaura.infused_iron_shoes.name=植物学家的靴子
item.naturesaura.effect_powder.naturesaura:plant_boost.name=稳定生长粉
item.naturesaura.effect_powder.naturesaura:cache_recharge.name=缓存补给粉
item.naturesaura.effect_powder.naturesaura:animal.name=增强繁殖粉
item.naturesaura.effect_powder.naturesaura:ore_spawn.name=矿物生成粉
item.naturesaura.mover_cart.name=吸灵矿车
item.naturesaura.range_visualizer.name=奥秘放大镜
item.naturesaura.clock_hand.name=时间之手
item.naturesaura.token_anger.name=愤怒人偶
item.naturesaura.token_euphoria.name=幸福人偶
item.naturesaura.token_fear.name=恐惧人偶
item.naturesaura.token_grief.name=悲伤人偶
item.naturesaura.token_joy.name=欢欣人偶
item.naturesaura.token_rage.name=狂怒人偶
item.naturesaura.token_sorrow.name=悲痛人偶
item.naturesaura.token_terror.name=恐怖人偶
item.naturesaura.ender_access.name=末影目镜
item.naturesaura.cave_finder.name=暗影执杖

container.naturesaura.tree_ritual.name=森林仪式
container.naturesaura.altar.name=自然祭坛
container.naturesaura.offering.name=神灵祭祀
container.naturesaura.animal_spawner.name=动物生成器

info.naturesaura.aura_in_area=灵气围绕着你
info.naturesaura.book.landing=$(aura) 是一种复杂的东西，制作、收集和利用它可能很困难$(br)这本 $(item)自然灵气宝典$() 里面包含了许多你想知道的所有信息。
info.naturesaura.book.subtitle=自然灵气指南
info.naturesaura.stored_pos=已标记了这个坐标
info.naturesaura.connected=已接通
info.naturesaura.same_position=这好像是你已经标记了的坐标......
info.naturesaura.too_far=距离太远了......
info.naturesaura.stored_pos_gone=你的标记已经过时......
info.naturesaura.empty=空的
info.naturesaura.ender_crate=末影板条箱: %s
info.naturesaura.ender_access=末影目镜: %s
info.naturesaura.ender_name.missing=没有该名称
info.naturesaura.ender_name=名称: %s

advancement.naturesaura.root=自然灵气
advancement.naturesaura.root.desc=成为一个魔法植物学家
advancement.naturesaura.get_book=充满灵气的一页！
advancement.naturesaura.get_book.desc=制作一本自然灵气宝典
advancement.naturesaura.gold_leaf=辉煌始于时间
advancement.naturesaura.gold_leaf.desc=制作并收获一颗闪耀之树
advancement.naturesaura.wood_stand=源自森林的力量！
advancement.naturesaura.wood_stand.desc=为森林仪式制作一个木桩
advancement.naturesaura.altar=权力
advancement.naturesaura.altar.desc=使用森林仪式制作一个自然祭坛
advancement.naturesaura.infused_materials=冶铁厂
advancement.naturesaura.infused_materials.desc=使用自然祭坛制作一个注灵铁锭
advancement.naturesaura.furnace_heater=越来越热
advancement.naturesaura.furnace_heater.desc=制作一个外置点火器来为你的熔炉提供热量
advancement.naturesaura.placer=啪嗒！啪嗒！
advancement.naturesaura.placer.desc=制作一个建筑者来为你放置方块
advancement.naturesaura.conversion_catalyst=大奸商！
advancement.naturesaura.conversion_catalyst.desc=制造一个易于材料转换的转型催化器
advancement.naturesaura.infused_tools=高质量的加速
advancement.naturesaura.infused_tools.desc=制作一把注灵的铁镐与注灵的铁剑
advancement.naturesaura.aura_bottle_overworld=阳光的味道
advancement.naturesaura.aura_bottle_overworld.desc=使用空瓶在主世界收集灵气
advancement.naturesaura.aura_bottle_nether=恐怖的骷髅
advancement.naturesaura.aura_bottle_nether.desc=使用空瓶在下界收集灵气
advancement.naturesaura.aura_bottle_end=仔细听，这是呼吸声
advancement.naturesaura.aura_bottle_end.desc=使用空瓶在末地收集灵气
advancement.naturesaura.offering=万能的主，您需要什么？
advancement.naturesaura.offering.desc=为献给神的祭品制作一个神灵祭坛
advancement.naturesaura.sky_ingot=轻巧又坚固
advancement.naturesaura.sky_ingot.desc=使用神灵祭坛制作一个苍穹之锭
advancement.naturesaura.aura_cache=我想把它存起来！
advancement.naturesaura.aura_cache.desc=制作一个灵气储存器以便将灵气存进去
advancement.naturesaura.positive_imbalance=甜甜蜜蜜的一天
advancement.naturesaura.positive_imbalance.desc=制作足够的灵气来产生积极的不平衡效果
advancement.naturesaura.negative_imbalance=痛不欲生的一天
advancement.naturesaura.negative_imbalance.desc=吸取足够的灵气来产生负面的不平衡效果
advancement.naturesaura.end_flower=蓝色妖姬
advancement.naturesaura.end_flower.desc=杀死末影龙，使忘忧玫瑰生长
advancement.naturesaura.eye=突然间，我看到了......
advancement.naturesaura.eye.desc=制作一个环境之眼来查看该区域的灵气
advancement.naturesaura.eye_improved=突然间，我看到的好多了！
advancement.naturesaura.eye_improved.desc=制作一个环境观测镜来查看灵气失衡的影响
advancement.naturesaura.range_visualizer=暗中观察！
advancement.naturesaura.range_visualizer.desc=制作一个奥秘放大镜来查看设备的作用范围

command.naturesaura.aura.usage=/naaura store|drain <数量> [范围] 或者 /naaura reset <范围>

potion.naturesaura.breathless.name=屏气

entity.naturesaura.effect_inhibitor.name=灵气粉末
entity.naturesaura.mover_cart.name=吸灵矿车

**Comment by Ellpeck** [comment]
Please create a pull request.

**Comment by ChirenCQR** [comment]
I know ,  but I sorry I don't know how to create a pull request ?

**Comment by ChirenCQR** [comment]
I know ,  but I sorry I don't know how to create a pull request ?

**Comment by ChirenCQR** [comment]
OK，I already how I should to do.
