### ISSUE TITLE
Crafttweaking + Book recipes

### ISSUE THREAD

**Issue by Fortist** [Ellpeck/NaturesAura#39]
Changing rituals or Altar recipes breaks the book by throwing an error in the opening GUI saying "error loading [insert ritual]" for example, changing the Ancient sapling recipe. or changing the Sugar cane to sugar recipe.

![2019-03-17_17 16 55](https://user-images.githubusercontent.com/5784537/54498060-87ccea00-48d8-11e9-8c78-3d74d98b34c1.png)

When trying to access certain entries or multiblocks crashes to main menu throwing a patchouli error.

**Comment by Ellpeck** [comment]
Are you giving the new recipes the same names as the old ones?
