### ISSUE TITLE
[Question] Unlocking through advancements

### ISSUE THREAD

**Issue by TimGoll** [Ellpeck/NaturesAura#4]
I'm currently creating a modpack which uses Triumph for custom advancements. It removes all the others. I could add your mod to a whitelist, but I'd like to implement my own advancements. The problem is: The chapters in your book are locked without the completition of the advancements
Would it be possible to add a config setting to unlock the book without completing advancements?

**Comment by Ellpeck** [comment]
There already is an option like that in Patchouli.

**Comment by TimGoll** [comment]
Oh, I haven't looked in it, thanks
