### ISSUE TITLE
Unable to create Disruption Catalyst

### ISSUE THREAD

**Issue by Zygus42** [Ellpeck/NaturesAura#40]
This might just be my stupidity, but the recipe for the Disruption Catalyst calls for a dark oak sapling to be grown in the center of the Ritual of the Forest - dark oak doesn't grow in a 1x1, has to be 2x2, but there's no space in the center of the ritual due to the gold powder.  I tried growing it anyway using bonemeal, but no luck.  I also tried a normal oak sapling and that didn't work either.

**Comment by Ellpeck** [comment]
There's no disruption catalyst in Nature's Aura.

**Comment by PolarizedIons** [comment]
Fixed in https://github.com/superaxander/Auraddons/commit/b284d2f083628001e6920697666e93e6e4696e2f

**Comment by Zygus42** [comment]
oops - my bad - jei shows clearly as addons :(
