### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by heiseshuishan** [Ellpeck/NaturesAura#41]
The following problem occurred when I opened the manual.
https://paste.ubuntu.com/p/Nwqr4V2pN5/

**Comment by Ellpeck** [comment]
Are you using CraftTweaker to change or remove any Nature's Aura recipes?

**Comment by heiseshuishan** [comment]
> Are you using CraftTweaker to change or remove any Nature's Aura recipes? If so, please read the [info file](https://github.com/Ellpeck/NaturesAura/blob/master/CraftTweakerCompat.md).

I didn't use CraftTweaker to change Nature's Aura recipes, I just opened the book of Nature's Aura.

**Comment by Ellpeck** [comment]
What language do you have your game set to and what other mods do you have installed?

**Comment by heiseshuishan** [comment]
> What language do you have your game set to and what other mods do you have installed?
I use Chinese in the game, I added a lot of mods.

**Comment by Ellpeck** [comment]
Try setting your language to US English and see if the issue persists.
