### ISSUE TITLE
[Craftweaker Compat] Error Parsing recipe 

### ISSUE THREAD

**Issue by JACOBFRANTZ** [Ellpeck/NaturesAura#42]
I might be dumb, but following: 

`mods.naturesaura.Altar.addRecipe(String name, IIngredient input, IItemStack output, IIngredient catalyst, int aura, int time)`

So, I added the String name (Taken from the JSON files), Added the imput (<astralsorcery:blockmarble>), Output (<naturesaura:infused_stone>) and not wanting to have a catalyst, I ended up with:

`//Infused Rock

mods.naturesaura.Altar.removeRecipe(<naturesaura:infused_stone>)

mods.naturesaura.Altar.addRecipe(naturesaura:infused_stone, <astralsorcery:blockmarble>, <naturesaura:infused_stone>, null, 10, 5)`

When I load the game with this script I get an error. When I remove it, I don't get the error, so Im sure its this recipe that's messing it up.

Am I doing something wrong?

**Comment by Quarris** [comment]
Strings need "", IIngredient need <>
mods.naturesaura.Altar.addRecipe("naturesaura:infused_stone", <astralsorcery:blockmarble>, <naturesaura:infused_stone>, null, 10, 5)
Look up some example of other CT recipes at https://crafttweaker.readthedocs.io/en/latest/#

**Comment by JACOBFRANTZ** [comment]
I do have the <>, I guess it didn't show up. I didn't know about the strings though, thanks!

**Comment by JACOBFRANTZ** [comment]
> mods.naturesaura.Altar.addRecipe(`"naturesaura:infused_stone"`, `<astralsorcery:blockmarble>`, `<naturesaura:infused_stone>`, null, 10, 5)


I just ran it, and it still has that error (Sadly) Anything else I can do to fix it? (I Tried running it without this script, and it didn't have the error)

**Comment by Ellpeck** [comment]
What's the error?

**Comment by JACOBFRANTZ** [comment]
The error:


[crafttweaker : SIDE_CLIENT]: Error parsing recipes.zs:136 -- ; expected


(The script is on that line, I can upload the full recipes file if you want) 

------------------

The Script being used: 

mods.naturesaura.Altar.addRecipe("naturesaura:infused_stone", <astralsorcery:blockmarble>, <naturesaura:infused_stone>, null, 10, 5)

(Its the same as Quarris')

------------


The log: 

[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: recipes.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 4ms
[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [contenttweaker]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [contenttweaker]
[PREINITIALIZATION][CLIENT][INFO] [contenttweaker | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: recipes.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 0ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [contenttweaker], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: recipes.zs}
[INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing recipes.zs:136 -- ; expected
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 303ms
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook

**Comment by Ellpeck** [comment]
It literally says "[semicolon] expected".

**Comment by JACOBFRANTZ** [comment]
Im an idiot, sorry for wasting your time. :P
