### ISSUE TITLE
Ancient Sapling Crashes world 

### ISSUE THREAD

**Issue by Zentraxius** [Ellpeck/NaturesAura#46]
Used creative mode to spawn in an ancient sapling, attempted to quickly grow it using bone meal - world immediately crashes and has to be shut down, reload and it brings world back up prior to ancient sapling being placed.

This was in a skyblock world made via void islands control

Made a 2nd world for testing on Superflat and spawned ancient sapling -> bone meal -> pretty tree.

Made a 3rd world in voidislands as a skyblock world for testing, spawned ancient tree and bonemealed it -> waiting for server -> we can't have nice things because it just got frozen on *waiting for server*

Last troubleshooting attempt I had made was making a 4th world and starting it as creative as opposed to Open to Lan -> Cheats Enabled and making sure the log was enabled to see if anything showed up in the fatal/error tab, nothing had loaded for several minutes prior to the crash before I had to task manager out. I gave it up to 10 minutes to load with no success.

Log has nothing, only crashes on void world spawned by voidislandcontrol, works on different worlds and can't figure out why.

**Comment by Zentraxius** [comment]
Update - if the tree has enough space it will grow even in a void world, smallest successful space seems to be 11x11x3 anything smaller and it will crash instead of loading

**Comment by Ellpeck** [comment]
Does it actually crash or does it just freeze? You're saying it crashes but then also you're saying there's nothing in the Log (so no crash report), which is impossible.

**Comment by Zentraxius** [comment]
My apologies - it freezes indefinitely until force closed.
