### ISSUE TITLE
[Feature Request] Remove blocks from oregen

### ISSUE THREAD

**Issue by martmists** [Ellpeck/NaturesAura#47]
For some reason, Nature's Aura misidentifies blocks as ores:

- Galacticraft's Tin Decoration Block
- Quark's Black Quartz Pillar

Additionally, it uses ores from multiple mods for the same ore, most notably:

- Thermal Foundation Copper+Tin Ore
- Railcraft Copper+Tin Ore

It is possible to ADD ores in the naturesaura.cfg file, but there is no option to remove blocks currently in the list. Please add this feature as this is unwanted behavior in modpacks.

**Comment by Ellpeck** [comment]
Nature's Aura's ore generation identifies everything as an ore that is classified in the Ore Dictionary with the prefix `ore`, as this is an official Forge convention. It looks like, in your modpack, for some reason, the two blocks you mentioned first have this ore classification when they shouldn't.

**Comment by martmists** [comment]
![2019-04-14_12 05 54](https://user-images.githubusercontent.com/16361449/56091324-c6d96580-5ead-11e9-8d24-a1ade7a15060.png)
![2019-04-14_12 06 03](https://user-images.githubusercontent.com/16361449/56091326-cccf4680-5ead-11e9-80f7-a50917870aea.png)

They don't seem to have any oredictionary entries with prefix `ore`

**Comment by martmists** [comment]
IC2 Basalt also seems to be generated
