### ISSUE TITLE
[Suggestion] Going green! In other words, recycle everything.

### ISSUE THREAD

**Issue by AssB0ys** [Ellpeck/NaturesAura#53]
It would be nice to see an ability to recycle every item in the game in exchange for something useful. Aura is the most obvious candidate, of course. Something like UU-matter fabricator from IC2 and the scrap recycler which is actually the block that takes any block or item in the game and has a chance to output the scrap which reduces the EU cost of UU-matter fabrication.
I imagine it like the brewing ritual where you throw potions at it, but instead of using potions you can drop anything at all and with some small chance get the aura back.

**Comment by JACOBFRANTZ** [comment]
So, like an aura making trashcan? That could be cool. (If a bit OP, you could just throw cobblestone in there)

**Comment by Mowmaster** [comment]
It'd be a pretty cool idea, but very OP for any item. Even if items have a % chance to return aura people would just farm the best option and feed it in. If it "remembered" what was trashed then maybe you could do diminishing returns. But that just adds more data to the tile.
