### ISSUE TITLE
shadows

### ISSUE THREAD

**Issue by mactso** [Ellpeck/NaturesAura#54]
In the current version of Magiculture 2 (0.5.0.6) the staff of shadows works a few times then stops working.

When I get a new staff in creative mode- that staff works and the staff that stopped working begins working again. They both have the same grey overlay timer showing the staff is cooling down.

Edit: And I can then delete the new staff that I got from creative mode and the original staff continues working (for a while- I haven't seen a pattern in why it stops working.

I'm not sure if it has limited charges.

**Comment by Ellpeck** [comment]
what

**Comment by mactso** [comment]
In the current version of Magiculture 2 (0.5.0.6) the staff of shadows works a few times then stops working.

When I get a new staff in creative mode- that staff works *and* the staff that stopped working begins working again.  They both have the same grey overlay timer showing the staff is cooling down.

I'm not sure if it has limited charges

**Comment by mactso** [comment]
Sorry... saved the issue by accident before I had typed in the details.

**Comment by Ellpeck** [comment]
What does this have to do with Nature's Aura?

**Comment by mactso** [comment]
The Staff of Shadows is nature's aura item.

It's the item that locates caves.

**Comment by Ellpeck** [comment]
What does this have to do with Magiculture? Does this issue not occur without it installed?

**Comment by mactso** [comment]
I don't know.  I'm doing nature's aura in the magiculture 2 modpack.  Just reporting that the item stops working after a few uses.  From what I can see it's not charged and getting a new staff in creative mode makes the staff that stopped working start working again.

Is the staff intended to only work a half dozen times?  I don't see a charge or durability indicator so I don't know.  Thanks.

**Comment by mactso** [comment]
I guess I'll report it as an issue to magiculture 2 instead.  Sorry to have bothered you.
