### ISSUE TITLE
Magical Progression Book Crash

### ISSUE THREAD

**Issue by bluewarbler** [Ellpeck/NaturesAura#56]
I'm playing with this mod in the Magical Progression modpack, version 3.5.0, with mod version r17.  I get the following crash when opening the Book of Nature's Aura to the section on the Natural Altar, the page after the one on Infused Iron:

https://pastebin.com/sYVcegqV

**Comment by periwinklerene** [comment]
Having the same problem. Has anyone gotten any news from the devs?

**Comment by Ellpeck** [comment]
Please update Nature's Aura and Patchouli to the newest versions and see if the issue remains.

**Comment by periwinklerene** [comment]
@Ellpeck Looked at the current file version and it was the most updates version, r17

![image](https://user-images.githubusercontent.com/36176511/67597269-bfd2c000-f738-11e9-91b0-00e613e003df.png)

**Comment by periwinklerene** [comment]
@Ellpeck thoughts?

**Comment by periwinklerene** [comment]
@Ellpeck hate to keep bothering you just wanted to check in to see if there's a fix on the way for this

**Comment by Ellpeck** [comment]
I'll get to it when I do, please stop bumping this thread for no reason
