### ISSUE TITLE
Integration with Pollution of the Realms?

### ISSUE THREAD

**Issue by duckwagon** [Ellpeck/NaturesAura#57]
How possible would some integration be with [Pollution of the Realms](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms?gameCategorySlug=mc-mods#c549)?

I'm thinking like just a simple add/subtract to the aura with the pollution levels in the mod, but I'm sure there's more you could do it. Seems like a really good fit.

**Comment by Ellpeck** [comment]
Nature's Aura has an extensive API, so it seems to make more sense for the author of that mod to add the integration.
