### ISSUE TITLE
Nature's Aura powered oak farm isn't aura positive

### ISSUE THREAD

**Issue by gchpaco** [Ellpeck/NaturesAura#58]
It seemed to me as well as others that an oak farm revolving around a canopy diminisher with aura field creators in the ground, planting trees on top of them, using repeaters to detect tree growth, and then activating the field creator and replacing stuff, *ought* to be aura positive.  But it is very slightly negative; the cost of creating the fields when a tree exists are heavier than the canopy diminisher can replenish.  It seems to me that this ought to work; perhaps the cost of starting up aura fields should be slightly cheaper?  I doubt you want to make the canopy diminisher more powerful, as that will further enable some-other-tree-farming-magic-block + canopy diminisher too much.

**Comment by Ellpeck** [comment]
This is intentional.
