### ISSUE TITLE
CraftTweaker TreeRitual doesn't work?

### ISSUE THREAD

**Issue by ZigTheHedge** [Ellpeck/NaturesAura#60]
Hi!

I can't find a way to make TreeRitual custom recipe work.

Here'e what I add to my .zs file. I can see the recipe in JEI, but I can't perform the ritual:

`mods.naturesaura.TreeRitual.addRecipe("time_ingot", <ore:treeSapling>, <theothersidecore:timeingot>, 700, [<ore:ingotPulsatingIron>, <ore:ingotPulsatingIron>, <ore:ingotNiobium>, <minecraft:nether_brick>, <minecraft:magma>, <minecraft:end_bricks>]);`

What am I doing wrong?

**Comment by Quarris** [comment]
I'm pretty sure the problem is that the names of items need to be surrounded by <>. So use <ore:treeSapling> and <theothersidecore:timeingot> for example

**Comment by Quarris** [comment]
Did you check the log file? crafttweaker has its own log in the modpack folder. It should tell you if something went wrong.

**Comment by ZigTheHedge** [comment]
@Quarris sure! Here's the log entry:

> [POSTINITIALIZATION][CLIENT][INFO] Adding 1 Tree Ritual Recipe(s) for <theothersidecore:timeingot>
[AVAILABLE][CLIENT][INFO] Fixed the RecipeBook

**Comment by Quarris** [comment]
huh

**Comment by ZigTheHedge** [comment]
Oh, I found an issue. It doesn't work with Spectre Sapling from "Random Things"... Works with vanilla saplings though.
