### ISSUE TITLE
Natural altar not working

### ISSUE THREAD

**Issue by PitBossX** [Ellpeck/NaturesAura#61]
I am playing Glacial awakening and my altar is not working. I used oak planks, stone bricks, chiseled stone bricks golden bricks and the altar. Aura not filling the altar and no glowing from the tops of the golden bricks. I have built it 4 times now to make sure i am doing it the right way but still not working.

**Comment by ByteTemplar** [comment]
I created the altar yesterday in Glacial awakening modpack and its working fine. Use the books ghost image system to make sure you build it right. One thing that was bit hard to see, was under the altar blockin middle is just dirt.

**Comment by Ellpeck** [comment]
Please post a screenshot of your setup with the F3 screen open.
