### ISSUE TITLE
Broken book progression

### ISSUE THREAD

**Issue by ItsMeDylan** [Ellpeck/NaturesAura#66]
After I put the leaf in the tree, I waited until it had completely turned into a golden tree and then I harvested it. Then I got the achievement Time=Brilliance, but the book will not unlock further. I even made a wood stand and captured sunlight but it wont progress further than the brilliant trees page. I have made the golden powder and i want to continue, but i don't know how.

**Comment by Ellpeck** [comment]
This is a Patchouli issue, but it might have been fixed for 1.14
