### ISSUE TITLE
No natural altar multiblock structure in guide book

### ISSUE THREAD

**Issue by warmthdawn** [Ellpeck/NaturesAura#67]
I am playing mystical sky and I find there are no description about natural altar's multiblock structure in the book.
I wonder if this is the modpack's problem.

**Comment by Ellpeck** [comment]
Can't reproduce

**Comment by Minamikaze392** [comment]
Where can I check the log?
![image](https://user-images.githubusercontent.com/40918110/74855126-398f5900-537b-11ea-9816-dc496b76b9b8.png)
