### ISSUE TITLE
[BUG]Placer cannot place blocks correctly

### ISSUE THREAD

**Issue by dong031001** [Ellpeck/NaturesAura#68]
## Description:
While playing, the placer can only place vanilla blocks, but not blocks in mods--even including blocks from the mod itself.
## Expected Behaiviour:
Correctly place modded blocks on the block that in the item frame.
## Screenshot:
This screenshot shall be fairly self-explainatory.

![2019-12-24_23 10 32](https://user-images.githubusercontent.com/30747164/71418012-5a04a500-26a3-11ea-8e79-518b0e7d7284.png)

**Comment by Ellpeck** [comment]
This was fixed as part of the 1.14 update
