### ISSUE TITLE
V1.14.4 java.lang.NullPointerException: mouseClicked event handler  *again*

### ISSUE THREAD

**Issue by Sos339** [Ellpeck/NaturesAura#71]
Paste
https://pastebin.com/dfDjyRe0

Updated mod to V20.0, same issue, clicking on any entry crashes minecraft (again)

**Comment by Ellpeck** [comment]
Are you playing in Singleplayer or on a dedicated server?

**Comment by Sos339** [comment]
Tested in singleplayer so far

**Comment by Sos339** [comment]
update v2
removing mods, adding mods back in, testing what the culprit is
the problem still is inconsistent with what mods I have and what I added in, and what world I used

**Comment by Ellpeck** [comment]
This was fixed through a fix in Patchouli
