### ISSUE TITLE
V1.14.4 java.lang.NullPointerException: mouseClicked event handler Crash (again)

### ISSUE THREAD

**Issue by Sos339** [Ellpeck/NaturesAura#72]
Paste
https://pastebin.com/dfDjyRe0

Updated mod to V20.0, same issue, clicking on any entry in the book crashes minecraft (again)

**Comment by Ellpeck** [comment]
ok but you don't have to post it twice

**Comment by Sos339** [comment]
ok I have no idea how it posted twice, my bad though
