### ISSUE TITLE
Client crash clicking links in the book

### ISSUE THREAD

**Issue by Renadarain** [Ellpeck/NaturesAura#74]
Hi :)

Minecraft 1.14.4
Forge: 1.14.4.28.1.117
Nature's Aura: 20.1

Client crashes on the server when clicking links in the book - looks to be Patchouli related.
https://pastebin.com/Eb5g8KL1

Regards,
Renada

**Comment by Ellpeck** [comment]
This is an issue with the most recent CurseForge release of Patchouli. Basically, you'll have to bug willie to release the fixed version :p
For now, you can get it here: https://ci.blamejared.com/job/Patchouli/job/master/135/

**Comment by Renadarain** [comment]
Hi :)

Thank you so much, it's much appreciated :)

Regards,
Renada
