### ISSUE TITLE
[Request] Server Performance Issue

### ISSUE THREAD

**Issue by xGarionx** [Ellpeck/NaturesAura#77]
Hi.
I'm Modpack Author of A.C.P and currently working on improving the server performance for the modpack, currently Natures Aura is the biggest taker of CPU useage i managed to reduces the intake from 15% down to 10% by tweaking particle emmit . Both Lagggoogles and Spark indentify
de.ellpeck.naturesaura.block.BlockSpawnLamp.onSpawn() method as the cullprint, 
We couldnt currently pin it down any further than that. 
Can you help us a bit to tweak the performance, while the server certainly can handle it, it still a bit concerning that a single mod causes this much server load (in a 252 big modpack).
![profile](https://user-images.githubusercontent.com/29960456/74583974-8666de80-4fcd-11ea-99c6-7745cf30e7d8.png)

**Comment by Ellpeck** [comment]
Yeea, that was kind of to be expected. Since the spawn lamp has a huge possible area, it also checks that huge area to see if any spawn lamps are nearby that would cancel the spawn. 
This is a pretty easy fix, though.

**Comment by xGarionx** [comment]
A easy fix would be highly appreciated ^^if you still need anything from me i can provide (logs etc.) just let me know, or if i can fix this on my end.

**Comment by Ellpeck** [comment]
Note that an update was released for the 1.12 version of the mod, and an update that includes this fix for the 1.15 version is coming soon :)

**Comment by xGarionx** [comment]
Thank you :D that what i call quick reaction
