### ISSUE TITLE
Ancient tree crashing server 1.15.2

### ISSUE THREAD

**Issue by LWalker111** [Ellpeck/NaturesAura#78]
Placing 2 or more trees close together in a world causes immediate server crashing when user gets close user can not join otherwise server crashes repeatedly

**Comment by Ellpeck** [comment]
Please submit the crash report.

**Comment by LWalker111** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/15/20 8:18 AM
Description: Exception in server tick loop

java.lang.ClassCastException: de.ellpeck.naturesaura.blocks.BlockDecayedLeaves cannot be cast to net.minecraft.block.LeavesBlock
	at net.olafkeijsers.fastleafdecay.FldScheduler.tick(FldScheduler.java:55) ~[?:v20] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:823) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 478044400 bytes (455 MB) / 2138701824 bytes (2039 MB) up to 5234491392 bytes (4992 MB)
	CPUs: 8
	JVM Flags: 15 total; -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:+UnlockExperimentalVMOptions -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:NewSize=84m -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -Xmx5G -Xms2G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.1.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.1
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		inftrading_1.15-1.0.jar Infinite Trading {inftrading@1.0 DONE}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 DONE}
		craftingstation-3.0.4.jar Crafting Station {craftingstation@3.0.4 DONE}
		janoeo-3.1.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.1.2 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		buzzierbees-1.1.3.jar Buzzier Bees {buzzierbees@1.1.3 DONE}
		Mekanism-1.15.2-9.9.9.401.jar Mekanism {mekanism@9.9.9 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		IndustrialAgriculture[Core]-1.15.2-1.5.4.jar Industrial Agriculture {industrialagriculture@1.15.2-1.5.4 DONE}
		reap-1.12.1.jar Reap Mod {reap@1.12.1 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		noautojump-1.15.2-1.jar No Auto-Jump {noautojump@1.15.2-1 DONE}
		invtweaks-1.15.2-1.0.0.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.0 DONE}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 DONE}
		CoffeeSpawner-1.15.1-6.0.0.jar Coffee Spawner {coffeespawner@1.15.1-6.0.0 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 DONE}
		NaturesCompass-1.15.1-1.8.3.jar Nature's Compass {naturescompass@1.15.1-1.8.3 DONE}
		premenuscreen-1.3.jar Pre Menu Screen {premenuscreen@1.3 DONE}
		gardentools-1.15.2-1.0.0.jar Garden Tools {gardentools@1.15.2-1.0.0 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		DungeonCrawl-1.15.2-1.6.1.jar Dungeon Crawl {dungeoncrawl@1.6.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		nhacampfire_1.15-1.5.jar No Hostiles Around Campfire {nhacampfire@1.5 DONE}
		mcjtylib-1.15-4.0.1-alpha.jar McJtyLib {mcjtylib@1.15-4.0.1-alpha DONE}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		MekanismGenerators-1.15.2-9.9.9.401.jar Mekanism: Generators {mekanismgenerators@9.9.9 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		CraftTweaker-1.15.1-6.0.0.5.jar CraftTweaker {crafttweaker@6.0.0.5 DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.1-universal.jar Forge {forge@31.1.1 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		absentbydesign-1.15.2-1.0.5 .jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 DONE}
		PackMenu-1.15.2-1.1.7.jar Pack Menu {packmenu@1.1.7 DONE}
		forge-1.15.2-31.1.1-server.jar Minecraft {minecraft@1.15.2 DONE}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 DONE}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		theoneprobe-1.15-2.0.0_1.jar The One Probe {theoneprobe@1.15-2.0.0 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE}
		SilentGear-1.15.2-1.5.1+76.jar Silent Gear {silentgear@1.5.1+76 DONE}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		Patchouli-1.15.2-1.2-27.jar Patchouli {patchouli@1.15.2-1.1-25 DONE}
		Xaeros_Minimap_20.2.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.2.0 DONE}
		JAOPCA-1.15.2-3.0.0.18.jar JAOPCA {jaopca@3.0.0.18 DONE}
		rftoolsstorage-1.15-1.0.1-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.1-alpha DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		tanknull-1.7.jar Tank Null {tanknull@1.7 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		elevatorid-1.15.2-1.6.1.jar Elevator Mod {elevatorid@1.15.2-1.6.1 DONE}
		tombstone-4.2.2-1.15.2.jar Corail Tombstone {tombstone@4.2.2 DONE}
		structurize-0.10.252-ALPHA.jar Structurize {structurize@0.10.252-ALPHA DONE}
		NaturesAura-21.0.jar Nature's Aura {naturesaura@version DONE}
		minecolonies-0.10.697-ALPHA-universal.jar Minecolonies {minecolonies@0.10.697-ALPHA DONE}
		MekanismTools-1.15.2-9.9.9.401.jar Mekanism: Tools {mekanismtools@9.9.9 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		World-Stripper-1.7.2-1.15.1.jar World Stripper {worldstripper@1.7.2 DONE}
		nosoliciting-1.1.jar No Soliciting {nosoliciting@1.1 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		Aquaculture-1.15.2-2.0.8.jar Aquaculture 2 {aquaculture@1.15.2-2.0.8 DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.5.2.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.5.2 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		CustomWindowTitle-1.15.2-v1.0.0.jar Custom Window Title {customwindowtitle@1.0.0 DONE}
		speedyladders-1.15.2-1.jar Speedy Ladders {speedyladders@1.15.2-1 DONE}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		SimpleDiscordRichPresence-1.15.2-1.2.4.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.4 DONE}
		Cyclic-1.15.2-0.1.8.jar Cyclic {cyclic@1.15.2-0.1.8 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 2 / 20; [ServerPlayerEntity['LWalker101'/43, l='world', x=-577.92, y=114.52, z=1687.87], ServerPlayerEntity['hughrc'/2817, l='world', x=-589.89, y=60.00, z=-1720.41]]
	Data Packs: vanilla, inmemory:jaopca (incompatible), mod:absentbydesign (incompatible), mod:aquaculture, mod:backpacked (incompatible), mod:betterbedrockgenerator, mod:bettertitlescreen, mod:bonsaitrees2, mod:bwncr (incompatible), mod:cloth-config2 (incompatible), mod:coffeespawner, mod:craftingstation (incompatible), mod:crafttweaker (incompatible), mod:cucumber, mod:customwindowtitle, mod:cyclic (incompatible), mod:dankstorage (incompatible), mod:dungeoncrawl (incompatible), mod:elevatorid (incompatible), mod:extradisks, mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:fastleafdecay, mod:forge (incompatible), mod:gardentools (incompatible), mod:iapmekanism, mod:industrialagriculture, mod:industrialforegoing (incompatible), mod:inftrading (incompatible), mod:ironjetpacks, mod:janoeo (incompatible), mod:jaopca (incompatible), mod:jei (incompatible), mod:kiwi, mod:kleeslabs (incompatible), mod:libnonymous (incompatible), mod:lightoverlay-forge (incompatible), mod:lostcities (incompatible), mod:mcjtylib (incompatible), mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:minecolonies (incompatible), mod:moredragoneggs, mod:mysticalagradditions, mod:mysticalagriculture, mod:naturescompass (incompatible), mod:nhacampfire (incompatible), mod:noautojump (incompatible), mod:nosoliciting (incompatible), mod:oreexcavation (incompatible), mod:packmenu (incompatible), mod:placebo (incompatible), mod:premenuscreen, mod:randompatches (incompatible), mod:rangedpumps (incompatible), mod:reap, mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:rftoolsbase (incompatible), mod:rftoolsbuilder (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolsutility (incompatible), mod:sdrp (incompatible), mod:servertabinfo (incompatible), mod:silentgear (incompatible), mod:silentlib (incompatible), mod:silents_mechanisms (incompatible), mod:simplechunkloaders (incompatible), mod:snowrealmagic, mod:solargeneration (incompatible), mod:speedyhoppers (incompatible), mod:speedyladders, mod:structurize (incompatible), mod:swingthroughgrass (incompatible), mod:tanknull (incompatible), mod:theoneprobe (incompatible), mod:titanium (incompatible), mod:tombstone, mod:valkyrielib (incompatible), mod:worldstripper (incompatible), mod:wstweaks (incompatible), mod:xaerominimap, mod:xaeroworldmap, mod:buzzierbees, mod:invtweaks (incompatible), mod:naturesaura (incompatible), mod:patchouli (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Ellpeck** [comment]
This is an issue with FastLeafDecay. It appears that it expects any block that returns true on `isLeaves` to automatically be an instance of `LeavesBlock`, which is not the case for Nature's Aura's decayed leaves.

**Comment by draco7858** [comment]
How exactly would you go about changing this?

**Comment by Quarris** [comment]
Its the fault of FastLeafDecay, there is no way to fix this on NatureAura's side

**Comment by draco7858** [comment]
No I mean like how would I

**Comment by Quarris** [comment]
You cant, you'll have to remove one of the mods. There really isn't an easy solution. You could somehow push the author of FastLeafDecay to fix it, but as you see I have mentioned this issue already a week ago and nothing. Possibly try finding a different mod which does the same job.

**Comment by Ellpeck** [comment]
Report the issue to fast leaf decay and/or remove the mod from your pack.
