### ISSUE TITLE
[1.14] Brilliant Fiber requires Tall Grass, which is unobtainable in vanilla MC

### ISSUE THREAD

**Issue by bshelden** [Ellpeck/NaturesAura#79]
The recipe for Brilliant Fiber requires tall grass, but that cannot be obtained in vanilla MC 1.14.  Shears on tall grass yields normal grass.

**Comment by Ellpeck** [comment]
Fixed by https://github.com/Ellpeck/NaturesAura/commit/5efcb7c9b22dd781c2a9577b2d3e012b1c2a02cc
