### ISSUE TITLE
[1.14.4] Crash when generating a world.

### ISSUE THREAD

**Issue by Gbergz** [Ellpeck/NaturesAura#80]
Title^

When generating a world it just gives up. Looking at the logs it appears it has crashed.

**Minecraft**: 1.14.4
**Forge**: 28.2.0
**Natures Aura Version**: 20.2
**Patchouli Version**: 1.1-26

**Crash-Report:**
https://gist.github.com/Gbergz/b62cc76a36a00d096c469c0d317fb7d6

**Full Logs:**
https://paste.gg/p/anonymous/8723f12567eb405c80ab4b1b36c9f358

Any ideas?
~ Gbergz

**Comment by Ellpeck** [comment]
The 1.14 version was just updated with a patch for this :)
