### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by kragnoth** [Ellpeck/NaturesAura#9]
Maybe have a form of craft tweaker integration where when a certain action is performed, it causes an increase or decrease in aura.

Like performing a blood magic ritual would decrease aura.  Or crafting industrial machines causes a decrease in aura near the crafting.

Being able to set the overall aura of a biome would also be awesome.  I.e. let a modpack maker set the aura to super low in a BoP wasteland biome, or super high in a magical biome.

**Comment by Ellpeck** [comment]
The system doesn't allow for and isn't designed for different amounts of Aura in different areas.
Additionally, I'm.. not quite sure how crafttweaker integration like that would look. If you want these features, you'll have to ask the devs of the respective mods you want the integration with to add them.
I'm sorry.

**Comment by kragnoth** [comment]
Alright, thanks.
