### ISSUE TITLE
[1.15.2] localization of manual in Chinese

### ISSUE THREAD

**Issue by EnterFor** [Ellpeck/NaturesAura#92]
From the team：https://cfpa.team/
The number of documents is a bit too much, I don't know which way is better to give to you
Can I just put it right here?
Only a few are untranslated

[zh_cn.zip](https://github.com/Ellpeck/NaturesAura/files/4332454/zh_cn.zip)

**Comment by EnterFor** [comment]
There are some problems

**Comment by Ellpeck** [comment]
Please create a pull request for this
