### ISSUE TITLE
CraftTweaker Bug

### ISSUE THREAD

**Issue by S1mpleM0use** [Ellpeck/NaturesAura#93]
I created a custom recipe for ancient sapling using ritual of the forest, and it displays in guide book, but i can't perform it. I already found why - because i left spaces just like in default recipe. Filling this spaces with any kind of item solves the problem, but i don't want to fill the whole 8 stands every time i am changing craft, especially if i am changing some kind of a bauble.

**Comment by S1mpleM0use** [comment]
As I want it to be
//new recipe for ancient sapling
import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
mods.naturesaura.TreeRitual.removeRecipe(<naturesaura:ancient_sapling>);
mods.naturesaura.TreeRitual.addRecipe("ancient_sapling", <ore:treeSapling>, <naturesaura:ancient_sapling>, 100, [<ore:treeSapling>, <botania:flower:6>, <botania:flower:2>, <minecraft:wheat_seeds>, <minecraft:reeds>, <naturesaura:gold_leaf>, null, null]);
How I must do now so it will work
//new recipe for ancient sapling
import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
mods.naturesaura.TreeRitual.removeRecipe(<naturesaura:ancient_sapling>);
mods.naturesaura.TreeRitual.addRecipe("ancient_sapling", <ore:treeSapling>, <naturesaura:ancient_sapling>, 100, [<ore:treeSapling>, <botania:flower:6>, <botania:flower:2>, <minecraft:wheat_seeds>, <minecraft:reeds>, <naturesaura:gold_leaf>, <ore:treeLeaves>, <ore:treeLeaves>]);

**Comment by Ellpeck** [comment]
You should be able to just shorten the array size instead of explicitly entering `null` values

**Comment by S1mpleM0use** [comment]
> You should be able to just shorten the array size instead of explicitly entering `null` values

Thanks!
