### ISSUE TITLE
[1.15.2-23.3] Client crash when using OpenBlocks Elevator to Nature's Aura area

### ISSUE THREAD

**Issue by shortybsd** [Ellpeck/NaturesAura#94]
**Minecraft:** 1.15.2
**Forge:** 31.1.18
**Nature's Aura:** 23.3
**OpenBlocks Elevator:** 1.7.0

When using elevator I receive the following [client crash](https://pastebin.com/Mkwe3QF2)

Not for sure why your mod tries to cast particles on the elevator block or who is at fault.

**Comment by Ellpeck** [comment]
This is not a Nature's Aura issue
