### ISSUE TITLE
[1.14.4 - 20.3] No natural altar multiblock structure

### ISSUE THREAD

**Issue by GSGDani** [Ellpeck/NaturesAura#99]
Hi, I have the same issue mentioned in #67 but can provide full client stacktrace. Modpack link, for reference: https://www.curseforge.com/minecraft/modpacks/game-server-germany-survival-server-modpack

**Minecraft:** 1.14.4
**Forge:** 28.2.3
**Natures Aura Version:** 20.3
**Patchouli Version:** 1.1-26

I'm not sure if patchouli related or NaturesAura, reporting here first.

**Stacktrace:** https://pastebin.com/VswsYXXF

Thanks!

**Comment by Ellpeck** [comment]
Please update the mod to the newest version before posting an issue report.
